// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddMediaToAlbum.proto

package gphotos;

public final class AddMediaToAlbumOuterClass {
  private AddMediaToAlbumOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddMediaToAlbumOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gphotos.AddMediaToAlbum)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string media_keys = 1;</code>
     * @return A list containing the mediaKeys.
     */
    java.util.List<java.lang.String>
        getMediaKeysList();
    /**
     * <code>repeated string media_keys = 1;</code>
     * @return The count of mediaKeys.
     */
    int getMediaKeysCount();
    /**
     * <code>repeated string media_keys = 1;</code>
     * @param index The index of the element to return.
     * @return The mediaKeys at the given index.
     */
    java.lang.String getMediaKeys(int index);
    /**
     * <code>repeated string media_keys = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the mediaKeys at the given index.
     */
    com.google.protobuf.ByteString
        getMediaKeysBytes(int index);

    /**
     * <code>string album_media_key = 2;</code>
     * @return The albumMediaKey.
     */
    java.lang.String getAlbumMediaKey();
    /**
     * <code>string album_media_key = 2;</code>
     * @return The bytes for albumMediaKey.
     */
    com.google.protobuf.ByteString
        getAlbumMediaKeyBytes();

    /**
     * <code>.gphotos.AddMediaToAlbum.Field5Type field5 = 5;</code>
     * @return Whether the field5 field is set.
     */
    boolean hasField5();
    /**
     * <code>.gphotos.AddMediaToAlbum.Field5Type field5 = 5;</code>
     * @return The field5.
     */
    gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type getField5();
    /**
     * <code>.gphotos.AddMediaToAlbum.Field5Type field5 = 5;</code>
     */
    gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5TypeOrBuilder getField5OrBuilder();

    /**
     * <code>.gphotos.AddMediaToAlbum.Field6Type device_info = 6;</code>
     * @return Whether the deviceInfo field is set.
     */
    boolean hasDeviceInfo();
    /**
     * <code>.gphotos.AddMediaToAlbum.Field6Type device_info = 6;</code>
     * @return The deviceInfo.
     */
    gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type getDeviceInfo();
    /**
     * <code>.gphotos.AddMediaToAlbum.Field6Type device_info = 6;</code>
     */
    gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6TypeOrBuilder getDeviceInfoOrBuilder();

    /**
     * <code>int64 timestamp = 7;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code gphotos.AddMediaToAlbum}
   */
  public static final class AddMediaToAlbum extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gphotos.AddMediaToAlbum)
      AddMediaToAlbumOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddMediaToAlbum.newBuilder() to construct.
    private AddMediaToAlbum(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddMediaToAlbum() {
      mediaKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      albumMediaKey_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AddMediaToAlbum();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gphotos.AddMediaToAlbumOuterClass.internal_static_gphotos_AddMediaToAlbum_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gphotos.AddMediaToAlbumOuterClass.internal_static_gphotos_AddMediaToAlbum_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.class, gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Builder.class);
    }

    public interface Field5TypeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:gphotos.AddMediaToAlbum.Field5Type)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int64 field1 = 1;</code>
       * @return The field1.
       */
      long getField1();
    }
    /**
     * Protobuf type {@code gphotos.AddMediaToAlbum.Field5Type}
     */
    public static final class Field5Type extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:gphotos.AddMediaToAlbum.Field5Type)
        Field5TypeOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Field5Type.newBuilder() to construct.
      private Field5Type(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Field5Type() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Field5Type();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gphotos.AddMediaToAlbumOuterClass.internal_static_gphotos_AddMediaToAlbum_Field5Type_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gphotos.AddMediaToAlbumOuterClass.internal_static_gphotos_AddMediaToAlbum_Field5Type_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type.class, gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type.Builder.class);
      }

      public static final int FIELD1_FIELD_NUMBER = 1;
      private long field1_ = 0L;
      /**
       * <code>int64 field1 = 1;</code>
       * @return The field1.
       */
      @java.lang.Override
      public long getField1() {
        return field1_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (field1_ != 0L) {
          output.writeInt64(1, field1_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (field1_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, field1_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type)) {
          return super.equals(obj);
        }
        gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type other = (gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type) obj;

        if (getField1()
            != other.getField1()) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + FIELD1_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getField1());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code gphotos.AddMediaToAlbum.Field5Type}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:gphotos.AddMediaToAlbum.Field5Type)
          gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5TypeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return gphotos.AddMediaToAlbumOuterClass.internal_static_gphotos_AddMediaToAlbum_Field5Type_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return gphotos.AddMediaToAlbumOuterClass.internal_static_gphotos_AddMediaToAlbum_Field5Type_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type.class, gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type.Builder.class);
        }

        // Construct using gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          field1_ = 0L;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return gphotos.AddMediaToAlbumOuterClass.internal_static_gphotos_AddMediaToAlbum_Field5Type_descriptor;
        }

        @java.lang.Override
        public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type getDefaultInstanceForType() {
          return gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type.getDefaultInstance();
        }

        @java.lang.Override
        public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type build() {
          gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type buildPartial() {
          gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type result = new gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.field1_ = field1_;
          }
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type) {
            return mergeFrom((gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type other) {
          if (other == gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type.getDefaultInstance()) return this;
          if (other.getField1() != 0L) {
            setField1(other.getField1());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 8: {
                  field1_ = input.readInt64();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 8
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private long field1_ ;
        /**
         * <code>int64 field1 = 1;</code>
         * @return The field1.
         */
        @java.lang.Override
        public long getField1() {
          return field1_;
        }
        /**
         * <code>int64 field1 = 1;</code>
         * @param value The field1 to set.
         * @return This builder for chaining.
         */
        public Builder setField1(long value) {
          
          field1_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>int64 field1 = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearField1() {
          bitField0_ = (bitField0_ & ~0x00000001);
          field1_ = 0L;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:gphotos.AddMediaToAlbum.Field5Type)
      }

      // @@protoc_insertion_point(class_scope:gphotos.AddMediaToAlbum.Field5Type)
      private static final gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type();
      }

      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Field5Type>
          PARSER = new com.google.protobuf.AbstractParser<Field5Type>() {
        @java.lang.Override
        public Field5Type parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<Field5Type> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Field5Type> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface Field6TypeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:gphotos.AddMediaToAlbum.Field6Type)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string model = 3;</code>
       * @return The model.
       */
      java.lang.String getModel();
      /**
       * <code>string model = 3;</code>
       * @return The bytes for model.
       */
      com.google.protobuf.ByteString
          getModelBytes();

      /**
       * <code>string make = 4;</code>
       * @return The make.
       */
      java.lang.String getMake();
      /**
       * <code>string make = 4;</code>
       * @return The bytes for make.
       */
      com.google.protobuf.ByteString
          getMakeBytes();

      /**
       * <code>int64 android_api_version = 5;</code>
       * @return The androidApiVersion.
       */
      long getAndroidApiVersion();
    }
    /**
     * Protobuf type {@code gphotos.AddMediaToAlbum.Field6Type}
     */
    public static final class Field6Type extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:gphotos.AddMediaToAlbum.Field6Type)
        Field6TypeOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Field6Type.newBuilder() to construct.
      private Field6Type(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Field6Type() {
        model_ = "";
        make_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Field6Type();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gphotos.AddMediaToAlbumOuterClass.internal_static_gphotos_AddMediaToAlbum_Field6Type_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gphotos.AddMediaToAlbumOuterClass.internal_static_gphotos_AddMediaToAlbum_Field6Type_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type.class, gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type.Builder.class);
      }

      public static final int MODEL_FIELD_NUMBER = 3;
      @SuppressWarnings("serial")
      private volatile java.lang.Object model_ = "";
      /**
       * <code>string model = 3;</code>
       * @return The model.
       */
      @java.lang.Override
      public java.lang.String getModel() {
        java.lang.Object ref = model_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          model_ = s;
          return s;
        }
      }
      /**
       * <code>string model = 3;</code>
       * @return The bytes for model.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getModelBytes() {
        java.lang.Object ref = model_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          model_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int MAKE_FIELD_NUMBER = 4;
      @SuppressWarnings("serial")
      private volatile java.lang.Object make_ = "";
      /**
       * <code>string make = 4;</code>
       * @return The make.
       */
      @java.lang.Override
      public java.lang.String getMake() {
        java.lang.Object ref = make_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          make_ = s;
          return s;
        }
      }
      /**
       * <code>string make = 4;</code>
       * @return The bytes for make.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMakeBytes() {
        java.lang.Object ref = make_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          make_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ANDROID_API_VERSION_FIELD_NUMBER = 5;
      private long androidApiVersion_ = 0L;
      /**
       * <code>int64 android_api_version = 5;</code>
       * @return The androidApiVersion.
       */
      @java.lang.Override
      public long getAndroidApiVersion() {
        return androidApiVersion_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(model_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, model_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(make_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, make_);
        }
        if (androidApiVersion_ != 0L) {
          output.writeInt64(5, androidApiVersion_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(model_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, model_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(make_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, make_);
        }
        if (androidApiVersion_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(5, androidApiVersion_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type)) {
          return super.equals(obj);
        }
        gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type other = (gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type) obj;

        if (!getModel()
            .equals(other.getModel())) return false;
        if (!getMake()
            .equals(other.getMake())) return false;
        if (getAndroidApiVersion()
            != other.getAndroidApiVersion()) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + MODEL_FIELD_NUMBER;
        hash = (53 * hash) + getModel().hashCode();
        hash = (37 * hash) + MAKE_FIELD_NUMBER;
        hash = (53 * hash) + getMake().hashCode();
        hash = (37 * hash) + ANDROID_API_VERSION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAndroidApiVersion());
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code gphotos.AddMediaToAlbum.Field6Type}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:gphotos.AddMediaToAlbum.Field6Type)
          gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6TypeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return gphotos.AddMediaToAlbumOuterClass.internal_static_gphotos_AddMediaToAlbum_Field6Type_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return gphotos.AddMediaToAlbumOuterClass.internal_static_gphotos_AddMediaToAlbum_Field6Type_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type.class, gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type.Builder.class);
        }

        // Construct using gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          model_ = "";
          make_ = "";
          androidApiVersion_ = 0L;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return gphotos.AddMediaToAlbumOuterClass.internal_static_gphotos_AddMediaToAlbum_Field6Type_descriptor;
        }

        @java.lang.Override
        public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type getDefaultInstanceForType() {
          return gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type.getDefaultInstance();
        }

        @java.lang.Override
        public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type build() {
          gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type buildPartial() {
          gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type result = new gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.model_ = model_;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.make_ = make_;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.androidApiVersion_ = androidApiVersion_;
          }
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type) {
            return mergeFrom((gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type other) {
          if (other == gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type.getDefaultInstance()) return this;
          if (!other.getModel().isEmpty()) {
            model_ = other.model_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          if (!other.getMake().isEmpty()) {
            make_ = other.make_;
            bitField0_ |= 0x00000002;
            onChanged();
          }
          if (other.getAndroidApiVersion() != 0L) {
            setAndroidApiVersion(other.getAndroidApiVersion());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 26: {
                  model_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 26
                case 34: {
                  make_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 34
                case 40: {
                  androidApiVersion_ = input.readInt64();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 40
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object model_ = "";
        /**
         * <code>string model = 3;</code>
         * @return The model.
         */
        public java.lang.String getModel() {
          java.lang.Object ref = model_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            model_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string model = 3;</code>
         * @return The bytes for model.
         */
        public com.google.protobuf.ByteString
            getModelBytes() {
          java.lang.Object ref = model_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            model_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string model = 3;</code>
         * @param value The model to set.
         * @return This builder for chaining.
         */
        public Builder setModel(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          model_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>string model = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearModel() {
          model_ = getDefaultInstance().getModel();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>string model = 3;</code>
         * @param value The bytes for model to set.
         * @return This builder for chaining.
         */
        public Builder setModelBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          model_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        private java.lang.Object make_ = "";
        /**
         * <code>string make = 4;</code>
         * @return The make.
         */
        public java.lang.String getMake() {
          java.lang.Object ref = make_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            make_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string make = 4;</code>
         * @return The bytes for make.
         */
        public com.google.protobuf.ByteString
            getMakeBytes() {
          java.lang.Object ref = make_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            make_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string make = 4;</code>
         * @param value The make to set.
         * @return This builder for chaining.
         */
        public Builder setMake(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          make_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>string make = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearMake() {
          make_ = getDefaultInstance().getMake();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>string make = 4;</code>
         * @param value The bytes for make to set.
         * @return This builder for chaining.
         */
        public Builder setMakeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          make_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }

        private long androidApiVersion_ ;
        /**
         * <code>int64 android_api_version = 5;</code>
         * @return The androidApiVersion.
         */
        @java.lang.Override
        public long getAndroidApiVersion() {
          return androidApiVersion_;
        }
        /**
         * <code>int64 android_api_version = 5;</code>
         * @param value The androidApiVersion to set.
         * @return This builder for chaining.
         */
        public Builder setAndroidApiVersion(long value) {
          
          androidApiVersion_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>int64 android_api_version = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearAndroidApiVersion() {
          bitField0_ = (bitField0_ & ~0x00000004);
          androidApiVersion_ = 0L;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:gphotos.AddMediaToAlbum.Field6Type)
      }

      // @@protoc_insertion_point(class_scope:gphotos.AddMediaToAlbum.Field6Type)
      private static final gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type();
      }

      public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Field6Type>
          PARSER = new com.google.protobuf.AbstractParser<Field6Type>() {
        @java.lang.Override
        public Field6Type parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<Field6Type> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Field6Type> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int MEDIA_KEYS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringList mediaKeys_;
    /**
     * <code>repeated string media_keys = 1;</code>
     * @return A list containing the mediaKeys.
     */
    public com.google.protobuf.ProtocolStringList
        getMediaKeysList() {
      return mediaKeys_;
    }
    /**
     * <code>repeated string media_keys = 1;</code>
     * @return The count of mediaKeys.
     */
    public int getMediaKeysCount() {
      return mediaKeys_.size();
    }
    /**
     * <code>repeated string media_keys = 1;</code>
     * @param index The index of the element to return.
     * @return The mediaKeys at the given index.
     */
    public java.lang.String getMediaKeys(int index) {
      return mediaKeys_.get(index);
    }
    /**
     * <code>repeated string media_keys = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the mediaKeys at the given index.
     */
    public com.google.protobuf.ByteString
        getMediaKeysBytes(int index) {
      return mediaKeys_.getByteString(index);
    }

    public static final int ALBUM_MEDIA_KEY_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object albumMediaKey_ = "";
    /**
     * <code>string album_media_key = 2;</code>
     * @return The albumMediaKey.
     */
    @java.lang.Override
    public java.lang.String getAlbumMediaKey() {
      java.lang.Object ref = albumMediaKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        albumMediaKey_ = s;
        return s;
      }
    }
    /**
     * <code>string album_media_key = 2;</code>
     * @return The bytes for albumMediaKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAlbumMediaKeyBytes() {
      java.lang.Object ref = albumMediaKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        albumMediaKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIELD5_FIELD_NUMBER = 5;
    private gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type field5_;
    /**
     * <code>.gphotos.AddMediaToAlbum.Field5Type field5 = 5;</code>
     * @return Whether the field5 field is set.
     */
    @java.lang.Override
    public boolean hasField5() {
      return field5_ != null;
    }
    /**
     * <code>.gphotos.AddMediaToAlbum.Field5Type field5 = 5;</code>
     * @return The field5.
     */
    @java.lang.Override
    public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type getField5() {
      return field5_ == null ? gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type.getDefaultInstance() : field5_;
    }
    /**
     * <code>.gphotos.AddMediaToAlbum.Field5Type field5 = 5;</code>
     */
    @java.lang.Override
    public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5TypeOrBuilder getField5OrBuilder() {
      return field5_ == null ? gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type.getDefaultInstance() : field5_;
    }

    public static final int DEVICE_INFO_FIELD_NUMBER = 6;
    private gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type deviceInfo_;
    /**
     * <code>.gphotos.AddMediaToAlbum.Field6Type device_info = 6;</code>
     * @return Whether the deviceInfo field is set.
     */
    @java.lang.Override
    public boolean hasDeviceInfo() {
      return deviceInfo_ != null;
    }
    /**
     * <code>.gphotos.AddMediaToAlbum.Field6Type device_info = 6;</code>
     * @return The deviceInfo.
     */
    @java.lang.Override
    public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type getDeviceInfo() {
      return deviceInfo_ == null ? gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type.getDefaultInstance() : deviceInfo_;
    }
    /**
     * <code>.gphotos.AddMediaToAlbum.Field6Type device_info = 6;</code>
     */
    @java.lang.Override
    public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6TypeOrBuilder getDeviceInfoOrBuilder() {
      return deviceInfo_ == null ? gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type.getDefaultInstance() : deviceInfo_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 7;
    private long timestamp_ = 0L;
    /**
     * <code>int64 timestamp = 7;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < mediaKeys_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mediaKeys_.getRaw(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(albumMediaKey_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, albumMediaKey_);
      }
      if (field5_ != null) {
        output.writeMessage(5, getField5());
      }
      if (deviceInfo_ != null) {
        output.writeMessage(6, getDeviceInfo());
      }
      if (timestamp_ != 0L) {
        output.writeInt64(7, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < mediaKeys_.size(); i++) {
          dataSize += computeStringSizeNoTag(mediaKeys_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMediaKeysList().size();
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(albumMediaKey_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, albumMediaKey_);
      }
      if (field5_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getField5());
      }
      if (deviceInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getDeviceInfo());
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum)) {
        return super.equals(obj);
      }
      gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum other = (gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum) obj;

      if (!getMediaKeysList()
          .equals(other.getMediaKeysList())) return false;
      if (!getAlbumMediaKey()
          .equals(other.getAlbumMediaKey())) return false;
      if (hasField5() != other.hasField5()) return false;
      if (hasField5()) {
        if (!getField5()
            .equals(other.getField5())) return false;
      }
      if (hasDeviceInfo() != other.hasDeviceInfo()) return false;
      if (hasDeviceInfo()) {
        if (!getDeviceInfo()
            .equals(other.getDeviceInfo())) return false;
      }
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMediaKeysCount() > 0) {
        hash = (37 * hash) + MEDIA_KEYS_FIELD_NUMBER;
        hash = (53 * hash) + getMediaKeysList().hashCode();
      }
      hash = (37 * hash) + ALBUM_MEDIA_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getAlbumMediaKey().hashCode();
      if (hasField5()) {
        hash = (37 * hash) + FIELD5_FIELD_NUMBER;
        hash = (53 * hash) + getField5().hashCode();
      }
      if (hasDeviceInfo()) {
        hash = (37 * hash) + DEVICE_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getDeviceInfo().hashCode();
      }
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gphotos.AddMediaToAlbum}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gphotos.AddMediaToAlbum)
        gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbumOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gphotos.AddMediaToAlbumOuterClass.internal_static_gphotos_AddMediaToAlbum_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gphotos.AddMediaToAlbumOuterClass.internal_static_gphotos_AddMediaToAlbum_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.class, gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Builder.class);
      }

      // Construct using gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        mediaKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        albumMediaKey_ = "";
        field5_ = null;
        if (field5Builder_ != null) {
          field5Builder_.dispose();
          field5Builder_ = null;
        }
        deviceInfo_ = null;
        if (deviceInfoBuilder_ != null) {
          deviceInfoBuilder_.dispose();
          deviceInfoBuilder_ = null;
        }
        timestamp_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gphotos.AddMediaToAlbumOuterClass.internal_static_gphotos_AddMediaToAlbum_descriptor;
      }

      @java.lang.Override
      public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum getDefaultInstanceForType() {
        return gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.getDefaultInstance();
      }

      @java.lang.Override
      public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum build() {
        gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum buildPartial() {
        gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum result = new gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum result) {
        if (((bitField0_ & 0x00000001) != 0)) {
          mediaKeys_ = mediaKeys_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.mediaKeys_ = mediaKeys_;
      }

      private void buildPartial0(gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.albumMediaKey_ = albumMediaKey_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.field5_ = field5Builder_ == null
              ? field5_
              : field5Builder_.build();
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.deviceInfo_ = deviceInfoBuilder_ == null
              ? deviceInfo_
              : deviceInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.timestamp_ = timestamp_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum) {
          return mergeFrom((gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum other) {
        if (other == gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.getDefaultInstance()) return this;
        if (!other.mediaKeys_.isEmpty()) {
          if (mediaKeys_.isEmpty()) {
            mediaKeys_ = other.mediaKeys_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMediaKeysIsMutable();
            mediaKeys_.addAll(other.mediaKeys_);
          }
          onChanged();
        }
        if (!other.getAlbumMediaKey().isEmpty()) {
          albumMediaKey_ = other.albumMediaKey_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasField5()) {
          mergeField5(other.getField5());
        }
        if (other.hasDeviceInfo()) {
          mergeDeviceInfo(other.getDeviceInfo());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureMediaKeysIsMutable();
                mediaKeys_.add(s);
                break;
              } // case 10
              case 18: {
                albumMediaKey_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 42: {
                input.readMessage(
                    getField5FieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 42
              case 50: {
                input.readMessage(
                    getDeviceInfoFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 50
              case 56: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList mediaKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMediaKeysIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          mediaKeys_ = new com.google.protobuf.LazyStringArrayList(mediaKeys_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string media_keys = 1;</code>
       * @return A list containing the mediaKeys.
       */
      public com.google.protobuf.ProtocolStringList
          getMediaKeysList() {
        return mediaKeys_.getUnmodifiableView();
      }
      /**
       * <code>repeated string media_keys = 1;</code>
       * @return The count of mediaKeys.
       */
      public int getMediaKeysCount() {
        return mediaKeys_.size();
      }
      /**
       * <code>repeated string media_keys = 1;</code>
       * @param index The index of the element to return.
       * @return The mediaKeys at the given index.
       */
      public java.lang.String getMediaKeys(int index) {
        return mediaKeys_.get(index);
      }
      /**
       * <code>repeated string media_keys = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the mediaKeys at the given index.
       */
      public com.google.protobuf.ByteString
          getMediaKeysBytes(int index) {
        return mediaKeys_.getByteString(index);
      }
      /**
       * <code>repeated string media_keys = 1;</code>
       * @param index The index to set the value at.
       * @param value The mediaKeys to set.
       * @return This builder for chaining.
       */
      public Builder setMediaKeys(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureMediaKeysIsMutable();
        mediaKeys_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string media_keys = 1;</code>
       * @param value The mediaKeys to add.
       * @return This builder for chaining.
       */
      public Builder addMediaKeys(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureMediaKeysIsMutable();
        mediaKeys_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string media_keys = 1;</code>
       * @param values The mediaKeys to add.
       * @return This builder for chaining.
       */
      public Builder addAllMediaKeys(
          java.lang.Iterable<java.lang.String> values) {
        ensureMediaKeysIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mediaKeys_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string media_keys = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMediaKeys() {
        mediaKeys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string media_keys = 1;</code>
       * @param value The bytes of the mediaKeys to add.
       * @return This builder for chaining.
       */
      public Builder addMediaKeysBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureMediaKeysIsMutable();
        mediaKeys_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object albumMediaKey_ = "";
      /**
       * <code>string album_media_key = 2;</code>
       * @return The albumMediaKey.
       */
      public java.lang.String getAlbumMediaKey() {
        java.lang.Object ref = albumMediaKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          albumMediaKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string album_media_key = 2;</code>
       * @return The bytes for albumMediaKey.
       */
      public com.google.protobuf.ByteString
          getAlbumMediaKeyBytes() {
        java.lang.Object ref = albumMediaKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          albumMediaKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string album_media_key = 2;</code>
       * @param value The albumMediaKey to set.
       * @return This builder for chaining.
       */
      public Builder setAlbumMediaKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        albumMediaKey_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string album_media_key = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlbumMediaKey() {
        albumMediaKey_ = getDefaultInstance().getAlbumMediaKey();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string album_media_key = 2;</code>
       * @param value The bytes for albumMediaKey to set.
       * @return This builder for chaining.
       */
      public Builder setAlbumMediaKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        albumMediaKey_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type field5_;
      private com.google.protobuf.SingleFieldBuilderV3<
          gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type, gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type.Builder, gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5TypeOrBuilder> field5Builder_;
      /**
       * <code>.gphotos.AddMediaToAlbum.Field5Type field5 = 5;</code>
       * @return Whether the field5 field is set.
       */
      public boolean hasField5() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.gphotos.AddMediaToAlbum.Field5Type field5 = 5;</code>
       * @return The field5.
       */
      public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type getField5() {
        if (field5Builder_ == null) {
          return field5_ == null ? gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type.getDefaultInstance() : field5_;
        } else {
          return field5Builder_.getMessage();
        }
      }
      /**
       * <code>.gphotos.AddMediaToAlbum.Field5Type field5 = 5;</code>
       */
      public Builder setField5(gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type value) {
        if (field5Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          field5_ = value;
        } else {
          field5Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.gphotos.AddMediaToAlbum.Field5Type field5 = 5;</code>
       */
      public Builder setField5(
          gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type.Builder builderForValue) {
        if (field5Builder_ == null) {
          field5_ = builderForValue.build();
        } else {
          field5Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.gphotos.AddMediaToAlbum.Field5Type field5 = 5;</code>
       */
      public Builder mergeField5(gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type value) {
        if (field5Builder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            field5_ != null &&
            field5_ != gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type.getDefaultInstance()) {
            getField5Builder().mergeFrom(value);
          } else {
            field5_ = value;
          }
        } else {
          field5Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.gphotos.AddMediaToAlbum.Field5Type field5 = 5;</code>
       */
      public Builder clearField5() {
        bitField0_ = (bitField0_ & ~0x00000004);
        field5_ = null;
        if (field5Builder_ != null) {
          field5Builder_.dispose();
          field5Builder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.gphotos.AddMediaToAlbum.Field5Type field5 = 5;</code>
       */
      public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type.Builder getField5Builder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getField5FieldBuilder().getBuilder();
      }
      /**
       * <code>.gphotos.AddMediaToAlbum.Field5Type field5 = 5;</code>
       */
      public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5TypeOrBuilder getField5OrBuilder() {
        if (field5Builder_ != null) {
          return field5Builder_.getMessageOrBuilder();
        } else {
          return field5_ == null ?
              gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type.getDefaultInstance() : field5_;
        }
      }
      /**
       * <code>.gphotos.AddMediaToAlbum.Field5Type field5 = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type, gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type.Builder, gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5TypeOrBuilder> 
          getField5FieldBuilder() {
        if (field5Builder_ == null) {
          field5Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type, gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5Type.Builder, gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field5TypeOrBuilder>(
                  getField5(),
                  getParentForChildren(),
                  isClean());
          field5_ = null;
        }
        return field5Builder_;
      }

      private gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type deviceInfo_;
      private com.google.protobuf.SingleFieldBuilderV3<
          gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type, gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type.Builder, gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6TypeOrBuilder> deviceInfoBuilder_;
      /**
       * <code>.gphotos.AddMediaToAlbum.Field6Type device_info = 6;</code>
       * @return Whether the deviceInfo field is set.
       */
      public boolean hasDeviceInfo() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.gphotos.AddMediaToAlbum.Field6Type device_info = 6;</code>
       * @return The deviceInfo.
       */
      public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type getDeviceInfo() {
        if (deviceInfoBuilder_ == null) {
          return deviceInfo_ == null ? gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type.getDefaultInstance() : deviceInfo_;
        } else {
          return deviceInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.gphotos.AddMediaToAlbum.Field6Type device_info = 6;</code>
       */
      public Builder setDeviceInfo(gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type value) {
        if (deviceInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          deviceInfo_ = value;
        } else {
          deviceInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.gphotos.AddMediaToAlbum.Field6Type device_info = 6;</code>
       */
      public Builder setDeviceInfo(
          gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type.Builder builderForValue) {
        if (deviceInfoBuilder_ == null) {
          deviceInfo_ = builderForValue.build();
        } else {
          deviceInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.gphotos.AddMediaToAlbum.Field6Type device_info = 6;</code>
       */
      public Builder mergeDeviceInfo(gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type value) {
        if (deviceInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            deviceInfo_ != null &&
            deviceInfo_ != gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type.getDefaultInstance()) {
            getDeviceInfoBuilder().mergeFrom(value);
          } else {
            deviceInfo_ = value;
          }
        } else {
          deviceInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.gphotos.AddMediaToAlbum.Field6Type device_info = 6;</code>
       */
      public Builder clearDeviceInfo() {
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceInfo_ = null;
        if (deviceInfoBuilder_ != null) {
          deviceInfoBuilder_.dispose();
          deviceInfoBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.gphotos.AddMediaToAlbum.Field6Type device_info = 6;</code>
       */
      public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type.Builder getDeviceInfoBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getDeviceInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.gphotos.AddMediaToAlbum.Field6Type device_info = 6;</code>
       */
      public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6TypeOrBuilder getDeviceInfoOrBuilder() {
        if (deviceInfoBuilder_ != null) {
          return deviceInfoBuilder_.getMessageOrBuilder();
        } else {
          return deviceInfo_ == null ?
              gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type.getDefaultInstance() : deviceInfo_;
        }
      }
      /**
       * <code>.gphotos.AddMediaToAlbum.Field6Type device_info = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type, gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type.Builder, gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6TypeOrBuilder> 
          getDeviceInfoFieldBuilder() {
        if (deviceInfoBuilder_ == null) {
          deviceInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type, gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6Type.Builder, gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum.Field6TypeOrBuilder>(
                  getDeviceInfo(),
                  getParentForChildren(),
                  isClean());
          deviceInfo_ = null;
        }
        return deviceInfoBuilder_;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 7;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 7;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gphotos.AddMediaToAlbum)
    }

    // @@protoc_insertion_point(class_scope:gphotos.AddMediaToAlbum)
    private static final gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum();
    }

    public static gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddMediaToAlbum>
        PARSER = new com.google.protobuf.AbstractParser<AddMediaToAlbum>() {
      @java.lang.Override
      public AddMediaToAlbum parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AddMediaToAlbum> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddMediaToAlbum> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public gphotos.AddMediaToAlbumOuterClass.AddMediaToAlbum getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gphotos_AddMediaToAlbum_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gphotos_AddMediaToAlbum_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gphotos_AddMediaToAlbum_Field5Type_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gphotos_AddMediaToAlbum_Field5Type_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gphotos_AddMediaToAlbum_Field6Type_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gphotos_AddMediaToAlbum_Field6Type_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025AddMediaToAlbum.proto\022\007gphotos\"\246\002\n\017Add" +
      "MediaToAlbum\022\022\n\nmedia_keys\030\001 \003(\t\022\027\n\017albu" +
      "m_media_key\030\002 \001(\t\0223\n\006field5\030\005 \001(\0132#.gpho" +
      "tos.AddMediaToAlbum.Field5Type\0228\n\013device" +
      "_info\030\006 \001(\0132#.gphotos.AddMediaToAlbum.Fi" +
      "eld6Type\022\021\n\ttimestamp\030\007 \001(\003\032\034\n\nField5Typ" +
      "e\022\016\n\006field1\030\001 \001(\003\032F\n\nField6Type\022\r\n\005model" +
      "\030\003 \001(\t\022\014\n\004make\030\004 \001(\t\022\033\n\023android_api_vers" +
      "ion\030\005 \001(\003B$\n\007gphotosB\031AddMediaToAlbumOut" +
      "erClassb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gphotos_AddMediaToAlbum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gphotos_AddMediaToAlbum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gphotos_AddMediaToAlbum_descriptor,
        new java.lang.String[] { "MediaKeys", "AlbumMediaKey", "Field5", "DeviceInfo", "Timestamp", });
    internal_static_gphotos_AddMediaToAlbum_Field5Type_descriptor =
      internal_static_gphotos_AddMediaToAlbum_descriptor.getNestedTypes().get(0);
    internal_static_gphotos_AddMediaToAlbum_Field5Type_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gphotos_AddMediaToAlbum_Field5Type_descriptor,
        new java.lang.String[] { "Field1", });
    internal_static_gphotos_AddMediaToAlbum_Field6Type_descriptor =
      internal_static_gphotos_AddMediaToAlbum_descriptor.getNestedTypes().get(1);
    internal_static_gphotos_AddMediaToAlbum_Field6Type_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gphotos_AddMediaToAlbum_Field6Type_descriptor,
        new java.lang.String[] { "Model", "Make", "AndroidApiVersion", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
