// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommitToken.proto

package gphotos;

public final class CommitTokenOuterClass {
  private CommitTokenOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommitTokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gphotos.CommitToken)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 field1 = 1;</code>
     * @return The field1.
     */
    long getField1();

    /**
     * <code>bytes field2 = 2;</code>
     * @return The field2.
     */
    com.google.protobuf.ByteString getField2();
  }
  /**
   * Protobuf type {@code gphotos.CommitToken}
   */
  public static final class CommitToken extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gphotos.CommitToken)
      CommitTokenOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommitToken.newBuilder() to construct.
    private CommitToken(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommitToken() {
      field2_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CommitToken();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gphotos.CommitTokenOuterClass.internal_static_gphotos_CommitToken_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gphotos.CommitTokenOuterClass.internal_static_gphotos_CommitToken_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gphotos.CommitTokenOuterClass.CommitToken.class, gphotos.CommitTokenOuterClass.CommitToken.Builder.class);
    }

    public static final int FIELD1_FIELD_NUMBER = 1;
    private long field1_ = 0L;
    /**
     * <code>int64 field1 = 1;</code>
     * @return The field1.
     */
    @java.lang.Override
    public long getField1() {
      return field1_;
    }

    public static final int FIELD2_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString field2_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes field2 = 2;</code>
     * @return The field2.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getField2() {
      return field2_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (field1_ != 0L) {
        output.writeInt64(1, field1_);
      }
      if (!field2_.isEmpty()) {
        output.writeBytes(2, field2_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (field1_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, field1_);
      }
      if (!field2_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, field2_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof gphotos.CommitTokenOuterClass.CommitToken)) {
        return super.equals(obj);
      }
      gphotos.CommitTokenOuterClass.CommitToken other = (gphotos.CommitTokenOuterClass.CommitToken) obj;

      if (getField1()
          != other.getField1()) return false;
      if (!getField2()
          .equals(other.getField2())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIELD1_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getField1());
      hash = (37 * hash) + FIELD2_FIELD_NUMBER;
      hash = (53 * hash) + getField2().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static gphotos.CommitTokenOuterClass.CommitToken parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gphotos.CommitTokenOuterClass.CommitToken parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gphotos.CommitTokenOuterClass.CommitToken parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gphotos.CommitTokenOuterClass.CommitToken parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gphotos.CommitTokenOuterClass.CommitToken parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gphotos.CommitTokenOuterClass.CommitToken parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gphotos.CommitTokenOuterClass.CommitToken parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gphotos.CommitTokenOuterClass.CommitToken parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static gphotos.CommitTokenOuterClass.CommitToken parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static gphotos.CommitTokenOuterClass.CommitToken parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static gphotos.CommitTokenOuterClass.CommitToken parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gphotos.CommitTokenOuterClass.CommitToken parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(gphotos.CommitTokenOuterClass.CommitToken prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gphotos.CommitToken}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gphotos.CommitToken)
        gphotos.CommitTokenOuterClass.CommitTokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gphotos.CommitTokenOuterClass.internal_static_gphotos_CommitToken_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gphotos.CommitTokenOuterClass.internal_static_gphotos_CommitToken_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gphotos.CommitTokenOuterClass.CommitToken.class, gphotos.CommitTokenOuterClass.CommitToken.Builder.class);
      }

      // Construct using gphotos.CommitTokenOuterClass.CommitToken.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        field1_ = 0L;
        field2_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gphotos.CommitTokenOuterClass.internal_static_gphotos_CommitToken_descriptor;
      }

      @java.lang.Override
      public gphotos.CommitTokenOuterClass.CommitToken getDefaultInstanceForType() {
        return gphotos.CommitTokenOuterClass.CommitToken.getDefaultInstance();
      }

      @java.lang.Override
      public gphotos.CommitTokenOuterClass.CommitToken build() {
        gphotos.CommitTokenOuterClass.CommitToken result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public gphotos.CommitTokenOuterClass.CommitToken buildPartial() {
        gphotos.CommitTokenOuterClass.CommitToken result = new gphotos.CommitTokenOuterClass.CommitToken(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(gphotos.CommitTokenOuterClass.CommitToken result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.field1_ = field1_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.field2_ = field2_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gphotos.CommitTokenOuterClass.CommitToken) {
          return mergeFrom((gphotos.CommitTokenOuterClass.CommitToken)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gphotos.CommitTokenOuterClass.CommitToken other) {
        if (other == gphotos.CommitTokenOuterClass.CommitToken.getDefaultInstance()) return this;
        if (other.getField1() != 0L) {
          setField1(other.getField1());
        }
        if (other.getField2() != com.google.protobuf.ByteString.EMPTY) {
          setField2(other.getField2());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                field1_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                field2_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long field1_ ;
      /**
       * <code>int64 field1 = 1;</code>
       * @return The field1.
       */
      @java.lang.Override
      public long getField1() {
        return field1_;
      }
      /**
       * <code>int64 field1 = 1;</code>
       * @param value The field1 to set.
       * @return This builder for chaining.
       */
      public Builder setField1(long value) {
        
        field1_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 field1 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearField1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        field1_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString field2_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes field2 = 2;</code>
       * @return The field2.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getField2() {
        return field2_;
      }
      /**
       * <code>bytes field2 = 2;</code>
       * @param value The field2 to set.
       * @return This builder for chaining.
       */
      public Builder setField2(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        field2_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes field2 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearField2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        field2_ = getDefaultInstance().getField2();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gphotos.CommitToken)
    }

    // @@protoc_insertion_point(class_scope:gphotos.CommitToken)
    private static final gphotos.CommitTokenOuterClass.CommitToken DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new gphotos.CommitTokenOuterClass.CommitToken();
    }

    public static gphotos.CommitTokenOuterClass.CommitToken getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommitToken>
        PARSER = new com.google.protobuf.AbstractParser<CommitToken>() {
      @java.lang.Override
      public CommitToken parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CommitToken> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommitToken> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public gphotos.CommitTokenOuterClass.CommitToken getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gphotos_CommitToken_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gphotos_CommitToken_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021CommitToken.proto\022\007gphotos\"-\n\013CommitTo" +
      "ken\022\016\n\006field1\030\001 \001(\003\022\016\n\006field2\030\002 \001(\014B \n\007g" +
      "photosB\025CommitTokenOuterClassb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gphotos_CommitToken_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gphotos_CommitToken_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gphotos_CommitToken_descriptor,
        new java.lang.String[] { "Field1", "Field2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
