// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CreateAlbumResponse.proto

package gphotos;

public final class CreateAlbumResponseOuterClass {
  private CreateAlbumResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CreateAlbumResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gphotos.CreateAlbumResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.gphotos.CreateAlbumResponse.Field1Type field1 = 1;</code>
     * @return Whether the field1 field is set.
     */
    boolean hasField1();
    /**
     * <code>.gphotos.CreateAlbumResponse.Field1Type field1 = 1;</code>
     * @return The field1.
     */
    gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type getField1();
    /**
     * <code>.gphotos.CreateAlbumResponse.Field1Type field1 = 1;</code>
     */
    gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1TypeOrBuilder getField1OrBuilder();

    /**
     * <code>repeated string field2 = 2;</code>
     * @return A list containing the field2.
     */
    java.util.List<java.lang.String>
        getField2List();
    /**
     * <code>repeated string field2 = 2;</code>
     * @return The count of field2.
     */
    int getField2Count();
    /**
     * <code>repeated string field2 = 2;</code>
     * @param index The index of the element to return.
     * @return The field2 at the given index.
     */
    java.lang.String getField2(int index);
    /**
     * <code>repeated string field2 = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the field2 at the given index.
     */
    com.google.protobuf.ByteString
        getField2Bytes(int index);
  }
  /**
   * Protobuf type {@code gphotos.CreateAlbumResponse}
   */
  public static final class CreateAlbumResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gphotos.CreateAlbumResponse)
      CreateAlbumResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreateAlbumResponse.newBuilder() to construct.
    private CreateAlbumResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateAlbumResponse() {
      field2_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CreateAlbumResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gphotos.CreateAlbumResponseOuterClass.internal_static_gphotos_CreateAlbumResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gphotos.CreateAlbumResponseOuterClass.internal_static_gphotos_CreateAlbumResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.class, gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Builder.class);
    }

    public interface Field1TypeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:gphotos.CreateAlbumResponse.Field1Type)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string album_media_key = 1;</code>
       * @return The albumMediaKey.
       */
      java.lang.String getAlbumMediaKey();
      /**
       * <code>string album_media_key = 1;</code>
       * @return The bytes for albumMediaKey.
       */
      com.google.protobuf.ByteString
          getAlbumMediaKeyBytes();
    }
    /**
     * Protobuf type {@code gphotos.CreateAlbumResponse.Field1Type}
     */
    public static final class Field1Type extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:gphotos.CreateAlbumResponse.Field1Type)
        Field1TypeOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Field1Type.newBuilder() to construct.
      private Field1Type(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Field1Type() {
        albumMediaKey_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Field1Type();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gphotos.CreateAlbumResponseOuterClass.internal_static_gphotos_CreateAlbumResponse_Field1Type_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gphotos.CreateAlbumResponseOuterClass.internal_static_gphotos_CreateAlbumResponse_Field1Type_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type.class, gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type.Builder.class);
      }

      public static final int ALBUM_MEDIA_KEY_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile java.lang.Object albumMediaKey_ = "";
      /**
       * <code>string album_media_key = 1;</code>
       * @return The albumMediaKey.
       */
      @java.lang.Override
      public java.lang.String getAlbumMediaKey() {
        java.lang.Object ref = albumMediaKey_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          albumMediaKey_ = s;
          return s;
        }
      }
      /**
       * <code>string album_media_key = 1;</code>
       * @return The bytes for albumMediaKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAlbumMediaKeyBytes() {
        java.lang.Object ref = albumMediaKey_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          albumMediaKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(albumMediaKey_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, albumMediaKey_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(albumMediaKey_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, albumMediaKey_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type)) {
          return super.equals(obj);
        }
        gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type other = (gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type) obj;

        if (!getAlbumMediaKey()
            .equals(other.getAlbumMediaKey())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ALBUM_MEDIA_KEY_FIELD_NUMBER;
        hash = (53 * hash) + getAlbumMediaKey().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code gphotos.CreateAlbumResponse.Field1Type}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:gphotos.CreateAlbumResponse.Field1Type)
          gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1TypeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return gphotos.CreateAlbumResponseOuterClass.internal_static_gphotos_CreateAlbumResponse_Field1Type_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return gphotos.CreateAlbumResponseOuterClass.internal_static_gphotos_CreateAlbumResponse_Field1Type_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type.class, gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type.Builder.class);
        }

        // Construct using gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          albumMediaKey_ = "";
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return gphotos.CreateAlbumResponseOuterClass.internal_static_gphotos_CreateAlbumResponse_Field1Type_descriptor;
        }

        @java.lang.Override
        public gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type getDefaultInstanceForType() {
          return gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type.getDefaultInstance();
        }

        @java.lang.Override
        public gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type build() {
          gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type buildPartial() {
          gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type result = new gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.albumMediaKey_ = albumMediaKey_;
          }
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type) {
            return mergeFrom((gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type other) {
          if (other == gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type.getDefaultInstance()) return this;
          if (!other.getAlbumMediaKey().isEmpty()) {
            albumMediaKey_ = other.albumMediaKey_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  albumMediaKey_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private java.lang.Object albumMediaKey_ = "";
        /**
         * <code>string album_media_key = 1;</code>
         * @return The albumMediaKey.
         */
        public java.lang.String getAlbumMediaKey() {
          java.lang.Object ref = albumMediaKey_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            albumMediaKey_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string album_media_key = 1;</code>
         * @return The bytes for albumMediaKey.
         */
        public com.google.protobuf.ByteString
            getAlbumMediaKeyBytes() {
          java.lang.Object ref = albumMediaKey_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            albumMediaKey_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string album_media_key = 1;</code>
         * @param value The albumMediaKey to set.
         * @return This builder for chaining.
         */
        public Builder setAlbumMediaKey(
            java.lang.String value) {
          if (value == null) { throw new NullPointerException(); }
          albumMediaKey_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>string album_media_key = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearAlbumMediaKey() {
          albumMediaKey_ = getDefaultInstance().getAlbumMediaKey();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>string album_media_key = 1;</code>
         * @param value The bytes for albumMediaKey to set.
         * @return This builder for chaining.
         */
        public Builder setAlbumMediaKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          albumMediaKey_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:gphotos.CreateAlbumResponse.Field1Type)
      }

      // @@protoc_insertion_point(class_scope:gphotos.CreateAlbumResponse.Field1Type)
      private static final gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type();
      }

      public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Field1Type>
          PARSER = new com.google.protobuf.AbstractParser<Field1Type>() {
        @java.lang.Override
        public Field1Type parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<Field1Type> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Field1Type> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int FIELD1_FIELD_NUMBER = 1;
    private gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type field1_;
    /**
     * <code>.gphotos.CreateAlbumResponse.Field1Type field1 = 1;</code>
     * @return Whether the field1 field is set.
     */
    @java.lang.Override
    public boolean hasField1() {
      return field1_ != null;
    }
    /**
     * <code>.gphotos.CreateAlbumResponse.Field1Type field1 = 1;</code>
     * @return The field1.
     */
    @java.lang.Override
    public gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type getField1() {
      return field1_ == null ? gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type.getDefaultInstance() : field1_;
    }
    /**
     * <code>.gphotos.CreateAlbumResponse.Field1Type field1 = 1;</code>
     */
    @java.lang.Override
    public gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1TypeOrBuilder getField1OrBuilder() {
      return field1_ == null ? gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type.getDefaultInstance() : field1_;
    }

    public static final int FIELD2_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringList field2_;
    /**
     * <code>repeated string field2 = 2;</code>
     * @return A list containing the field2.
     */
    public com.google.protobuf.ProtocolStringList
        getField2List() {
      return field2_;
    }
    /**
     * <code>repeated string field2 = 2;</code>
     * @return The count of field2.
     */
    public int getField2Count() {
      return field2_.size();
    }
    /**
     * <code>repeated string field2 = 2;</code>
     * @param index The index of the element to return.
     * @return The field2 at the given index.
     */
    public java.lang.String getField2(int index) {
      return field2_.get(index);
    }
    /**
     * <code>repeated string field2 = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the field2 at the given index.
     */
    public com.google.protobuf.ByteString
        getField2Bytes(int index) {
      return field2_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (field1_ != null) {
        output.writeMessage(1, getField1());
      }
      for (int i = 0; i < field2_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, field2_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (field1_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getField1());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < field2_.size(); i++) {
          dataSize += computeStringSizeNoTag(field2_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getField2List().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse)) {
        return super.equals(obj);
      }
      gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse other = (gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse) obj;

      if (hasField1() != other.hasField1()) return false;
      if (hasField1()) {
        if (!getField1()
            .equals(other.getField1())) return false;
      }
      if (!getField2List()
          .equals(other.getField2List())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasField1()) {
        hash = (37 * hash) + FIELD1_FIELD_NUMBER;
        hash = (53 * hash) + getField1().hashCode();
      }
      if (getField2Count() > 0) {
        hash = (37 * hash) + FIELD2_FIELD_NUMBER;
        hash = (53 * hash) + getField2List().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gphotos.CreateAlbumResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gphotos.CreateAlbumResponse)
        gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gphotos.CreateAlbumResponseOuterClass.internal_static_gphotos_CreateAlbumResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gphotos.CreateAlbumResponseOuterClass.internal_static_gphotos_CreateAlbumResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.class, gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Builder.class);
      }

      // Construct using gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        field1_ = null;
        if (field1Builder_ != null) {
          field1Builder_.dispose();
          field1Builder_ = null;
        }
        field2_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gphotos.CreateAlbumResponseOuterClass.internal_static_gphotos_CreateAlbumResponse_descriptor;
      }

      @java.lang.Override
      public gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse getDefaultInstanceForType() {
        return gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.getDefaultInstance();
      }

      @java.lang.Override
      public gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse build() {
        gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse buildPartial() {
        gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse result = new gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse result) {
        if (((bitField0_ & 0x00000002) != 0)) {
          field2_ = field2_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.field2_ = field2_;
      }

      private void buildPartial0(gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.field1_ = field1Builder_ == null
              ? field1_
              : field1Builder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse) {
          return mergeFrom((gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse other) {
        if (other == gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.getDefaultInstance()) return this;
        if (other.hasField1()) {
          mergeField1(other.getField1());
        }
        if (!other.field2_.isEmpty()) {
          if (field2_.isEmpty()) {
            field2_ = other.field2_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureField2IsMutable();
            field2_.addAll(other.field2_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getField1FieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureField2IsMutable();
                field2_.add(s);
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type field1_;
      private com.google.protobuf.SingleFieldBuilderV3<
          gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type, gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type.Builder, gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1TypeOrBuilder> field1Builder_;
      /**
       * <code>.gphotos.CreateAlbumResponse.Field1Type field1 = 1;</code>
       * @return Whether the field1 field is set.
       */
      public boolean hasField1() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.gphotos.CreateAlbumResponse.Field1Type field1 = 1;</code>
       * @return The field1.
       */
      public gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type getField1() {
        if (field1Builder_ == null) {
          return field1_ == null ? gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type.getDefaultInstance() : field1_;
        } else {
          return field1Builder_.getMessage();
        }
      }
      /**
       * <code>.gphotos.CreateAlbumResponse.Field1Type field1 = 1;</code>
       */
      public Builder setField1(gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type value) {
        if (field1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          field1_ = value;
        } else {
          field1Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.gphotos.CreateAlbumResponse.Field1Type field1 = 1;</code>
       */
      public Builder setField1(
          gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type.Builder builderForValue) {
        if (field1Builder_ == null) {
          field1_ = builderForValue.build();
        } else {
          field1Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.gphotos.CreateAlbumResponse.Field1Type field1 = 1;</code>
       */
      public Builder mergeField1(gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type value) {
        if (field1Builder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            field1_ != null &&
            field1_ != gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type.getDefaultInstance()) {
            getField1Builder().mergeFrom(value);
          } else {
            field1_ = value;
          }
        } else {
          field1Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.gphotos.CreateAlbumResponse.Field1Type field1 = 1;</code>
       */
      public Builder clearField1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        field1_ = null;
        if (field1Builder_ != null) {
          field1Builder_.dispose();
          field1Builder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.gphotos.CreateAlbumResponse.Field1Type field1 = 1;</code>
       */
      public gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type.Builder getField1Builder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getField1FieldBuilder().getBuilder();
      }
      /**
       * <code>.gphotos.CreateAlbumResponse.Field1Type field1 = 1;</code>
       */
      public gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1TypeOrBuilder getField1OrBuilder() {
        if (field1Builder_ != null) {
          return field1Builder_.getMessageOrBuilder();
        } else {
          return field1_ == null ?
              gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type.getDefaultInstance() : field1_;
        }
      }
      /**
       * <code>.gphotos.CreateAlbumResponse.Field1Type field1 = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type, gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type.Builder, gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1TypeOrBuilder> 
          getField1FieldBuilder() {
        if (field1Builder_ == null) {
          field1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type, gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1Type.Builder, gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse.Field1TypeOrBuilder>(
                  getField1(),
                  getParentForChildren(),
                  isClean());
          field1_ = null;
        }
        return field1Builder_;
      }

      private com.google.protobuf.LazyStringList field2_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureField2IsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          field2_ = new com.google.protobuf.LazyStringArrayList(field2_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string field2 = 2;</code>
       * @return A list containing the field2.
       */
      public com.google.protobuf.ProtocolStringList
          getField2List() {
        return field2_.getUnmodifiableView();
      }
      /**
       * <code>repeated string field2 = 2;</code>
       * @return The count of field2.
       */
      public int getField2Count() {
        return field2_.size();
      }
      /**
       * <code>repeated string field2 = 2;</code>
       * @param index The index of the element to return.
       * @return The field2 at the given index.
       */
      public java.lang.String getField2(int index) {
        return field2_.get(index);
      }
      /**
       * <code>repeated string field2 = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the field2 at the given index.
       */
      public com.google.protobuf.ByteString
          getField2Bytes(int index) {
        return field2_.getByteString(index);
      }
      /**
       * <code>repeated string field2 = 2;</code>
       * @param index The index to set the value at.
       * @param value The field2 to set.
       * @return This builder for chaining.
       */
      public Builder setField2(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureField2IsMutable();
        field2_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field2 = 2;</code>
       * @param value The field2 to add.
       * @return This builder for chaining.
       */
      public Builder addField2(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureField2IsMutable();
        field2_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field2 = 2;</code>
       * @param values The field2 to add.
       * @return This builder for chaining.
       */
      public Builder addAllField2(
          java.lang.Iterable<java.lang.String> values) {
        ensureField2IsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, field2_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field2 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearField2() {
        field2_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string field2 = 2;</code>
       * @param value The bytes of the field2 to add.
       * @return This builder for chaining.
       */
      public Builder addField2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureField2IsMutable();
        field2_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gphotos.CreateAlbumResponse)
    }

    // @@protoc_insertion_point(class_scope:gphotos.CreateAlbumResponse)
    private static final gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse();
    }

    public static gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateAlbumResponse>
        PARSER = new com.google.protobuf.AbstractParser<CreateAlbumResponse>() {
      @java.lang.Override
      public CreateAlbumResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CreateAlbumResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateAlbumResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public gphotos.CreateAlbumResponseOuterClass.CreateAlbumResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gphotos_CreateAlbumResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gphotos_CreateAlbumResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gphotos_CreateAlbumResponse_Field1Type_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gphotos_CreateAlbumResponse_Field1Type_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031CreateAlbumResponse.proto\022\007gphotos\"\205\001\n" +
      "\023CreateAlbumResponse\0227\n\006field1\030\001 \001(\0132\'.g" +
      "photos.CreateAlbumResponse.Field1Type\022\016\n" +
      "\006field2\030\002 \003(\t\032%\n\nField1Type\022\027\n\017album_med" +
      "ia_key\030\001 \001(\tB(\n\007gphotosB\035CreateAlbumResp" +
      "onseOuterClassb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gphotos_CreateAlbumResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gphotos_CreateAlbumResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gphotos_CreateAlbumResponse_descriptor,
        new java.lang.String[] { "Field1", "Field2", });
    internal_static_gphotos_CreateAlbumResponse_Field1Type_descriptor =
      internal_static_gphotos_CreateAlbumResponse_descriptor.getNestedTypes().get(0);
    internal_static_gphotos_CreateAlbumResponse_Field1Type_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gphotos_CreateAlbumResponse_Field1Type_descriptor,
        new java.lang.String[] { "AlbumMediaKey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
