// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetUploadToken.proto

package gphotos;

public final class GetUploadTokenOuterClass {
  private GetUploadTokenOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetUploadTokenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gphotos.GetUploadToken)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 f1 = 1;</code>
     * @return The f1.
     */
    int getF1();

    /**
     * <code>int32 f2 = 2;</code>
     * @return The f2.
     */
    int getF2();

    /**
     * <code>int32 f3 = 3;</code>
     * @return The f3.
     */
    int getF3();

    /**
     * <code>int32 f4 = 4;</code>
     * @return The f4.
     */
    int getF4();

    /**
     * <code>int64 file_size_bytes = 7;</code>
     * @return The fileSizeBytes.
     */
    long getFileSizeBytes();
  }
  /**
   * Protobuf type {@code gphotos.GetUploadToken}
   */
  public static final class GetUploadToken extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gphotos.GetUploadToken)
      GetUploadTokenOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetUploadToken.newBuilder() to construct.
    private GetUploadToken(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetUploadToken() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetUploadToken();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gphotos.GetUploadTokenOuterClass.internal_static_gphotos_GetUploadToken_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gphotos.GetUploadTokenOuterClass.internal_static_gphotos_GetUploadToken_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gphotos.GetUploadTokenOuterClass.GetUploadToken.class, gphotos.GetUploadTokenOuterClass.GetUploadToken.Builder.class);
    }

    public static final int F1_FIELD_NUMBER = 1;
    private int f1_ = 0;
    /**
     * <code>int32 f1 = 1;</code>
     * @return The f1.
     */
    @java.lang.Override
    public int getF1() {
      return f1_;
    }

    public static final int F2_FIELD_NUMBER = 2;
    private int f2_ = 0;
    /**
     * <code>int32 f2 = 2;</code>
     * @return The f2.
     */
    @java.lang.Override
    public int getF2() {
      return f2_;
    }

    public static final int F3_FIELD_NUMBER = 3;
    private int f3_ = 0;
    /**
     * <code>int32 f3 = 3;</code>
     * @return The f3.
     */
    @java.lang.Override
    public int getF3() {
      return f3_;
    }

    public static final int F4_FIELD_NUMBER = 4;
    private int f4_ = 0;
    /**
     * <code>int32 f4 = 4;</code>
     * @return The f4.
     */
    @java.lang.Override
    public int getF4() {
      return f4_;
    }

    public static final int FILE_SIZE_BYTES_FIELD_NUMBER = 7;
    private long fileSizeBytes_ = 0L;
    /**
     * <code>int64 file_size_bytes = 7;</code>
     * @return The fileSizeBytes.
     */
    @java.lang.Override
    public long getFileSizeBytes() {
      return fileSizeBytes_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (f1_ != 0) {
        output.writeInt32(1, f1_);
      }
      if (f2_ != 0) {
        output.writeInt32(2, f2_);
      }
      if (f3_ != 0) {
        output.writeInt32(3, f3_);
      }
      if (f4_ != 0) {
        output.writeInt32(4, f4_);
      }
      if (fileSizeBytes_ != 0L) {
        output.writeInt64(7, fileSizeBytes_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (f1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, f1_);
      }
      if (f2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, f2_);
      }
      if (f3_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, f3_);
      }
      if (f4_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, f4_);
      }
      if (fileSizeBytes_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, fileSizeBytes_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof gphotos.GetUploadTokenOuterClass.GetUploadToken)) {
        return super.equals(obj);
      }
      gphotos.GetUploadTokenOuterClass.GetUploadToken other = (gphotos.GetUploadTokenOuterClass.GetUploadToken) obj;

      if (getF1()
          != other.getF1()) return false;
      if (getF2()
          != other.getF2()) return false;
      if (getF3()
          != other.getF3()) return false;
      if (getF4()
          != other.getF4()) return false;
      if (getFileSizeBytes()
          != other.getFileSizeBytes()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + F1_FIELD_NUMBER;
      hash = (53 * hash) + getF1();
      hash = (37 * hash) + F2_FIELD_NUMBER;
      hash = (53 * hash) + getF2();
      hash = (37 * hash) + F3_FIELD_NUMBER;
      hash = (53 * hash) + getF3();
      hash = (37 * hash) + F4_FIELD_NUMBER;
      hash = (53 * hash) + getF4();
      hash = (37 * hash) + FILE_SIZE_BYTES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFileSizeBytes());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static gphotos.GetUploadTokenOuterClass.GetUploadToken parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gphotos.GetUploadTokenOuterClass.GetUploadToken parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gphotos.GetUploadTokenOuterClass.GetUploadToken parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gphotos.GetUploadTokenOuterClass.GetUploadToken parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gphotos.GetUploadTokenOuterClass.GetUploadToken parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gphotos.GetUploadTokenOuterClass.GetUploadToken parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gphotos.GetUploadTokenOuterClass.GetUploadToken parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gphotos.GetUploadTokenOuterClass.GetUploadToken parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static gphotos.GetUploadTokenOuterClass.GetUploadToken parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static gphotos.GetUploadTokenOuterClass.GetUploadToken parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static gphotos.GetUploadTokenOuterClass.GetUploadToken parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gphotos.GetUploadTokenOuterClass.GetUploadToken parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(gphotos.GetUploadTokenOuterClass.GetUploadToken prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gphotos.GetUploadToken}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gphotos.GetUploadToken)
        gphotos.GetUploadTokenOuterClass.GetUploadTokenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gphotos.GetUploadTokenOuterClass.internal_static_gphotos_GetUploadToken_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gphotos.GetUploadTokenOuterClass.internal_static_gphotos_GetUploadToken_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gphotos.GetUploadTokenOuterClass.GetUploadToken.class, gphotos.GetUploadTokenOuterClass.GetUploadToken.Builder.class);
      }

      // Construct using gphotos.GetUploadTokenOuterClass.GetUploadToken.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        f1_ = 0;
        f2_ = 0;
        f3_ = 0;
        f4_ = 0;
        fileSizeBytes_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gphotos.GetUploadTokenOuterClass.internal_static_gphotos_GetUploadToken_descriptor;
      }

      @java.lang.Override
      public gphotos.GetUploadTokenOuterClass.GetUploadToken getDefaultInstanceForType() {
        return gphotos.GetUploadTokenOuterClass.GetUploadToken.getDefaultInstance();
      }

      @java.lang.Override
      public gphotos.GetUploadTokenOuterClass.GetUploadToken build() {
        gphotos.GetUploadTokenOuterClass.GetUploadToken result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public gphotos.GetUploadTokenOuterClass.GetUploadToken buildPartial() {
        gphotos.GetUploadTokenOuterClass.GetUploadToken result = new gphotos.GetUploadTokenOuterClass.GetUploadToken(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(gphotos.GetUploadTokenOuterClass.GetUploadToken result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.f1_ = f1_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.f2_ = f2_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.f3_ = f3_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.f4_ = f4_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.fileSizeBytes_ = fileSizeBytes_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gphotos.GetUploadTokenOuterClass.GetUploadToken) {
          return mergeFrom((gphotos.GetUploadTokenOuterClass.GetUploadToken)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gphotos.GetUploadTokenOuterClass.GetUploadToken other) {
        if (other == gphotos.GetUploadTokenOuterClass.GetUploadToken.getDefaultInstance()) return this;
        if (other.getF1() != 0) {
          setF1(other.getF1());
        }
        if (other.getF2() != 0) {
          setF2(other.getF2());
        }
        if (other.getF3() != 0) {
          setF3(other.getF3());
        }
        if (other.getF4() != 0) {
          setF4(other.getF4());
        }
        if (other.getFileSizeBytes() != 0L) {
          setFileSizeBytes(other.getFileSizeBytes());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                f1_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                f2_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                f3_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                f4_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 56: {
                fileSizeBytes_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int f1_ ;
      /**
       * <code>int32 f1 = 1;</code>
       * @return The f1.
       */
      @java.lang.Override
      public int getF1() {
        return f1_;
      }
      /**
       * <code>int32 f1 = 1;</code>
       * @param value The f1 to set.
       * @return This builder for chaining.
       */
      public Builder setF1(int value) {
        
        f1_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 f1 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearF1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        f1_ = 0;
        onChanged();
        return this;
      }

      private int f2_ ;
      /**
       * <code>int32 f2 = 2;</code>
       * @return The f2.
       */
      @java.lang.Override
      public int getF2() {
        return f2_;
      }
      /**
       * <code>int32 f2 = 2;</code>
       * @param value The f2 to set.
       * @return This builder for chaining.
       */
      public Builder setF2(int value) {
        
        f2_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 f2 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearF2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        f2_ = 0;
        onChanged();
        return this;
      }

      private int f3_ ;
      /**
       * <code>int32 f3 = 3;</code>
       * @return The f3.
       */
      @java.lang.Override
      public int getF3() {
        return f3_;
      }
      /**
       * <code>int32 f3 = 3;</code>
       * @param value The f3 to set.
       * @return This builder for chaining.
       */
      public Builder setF3(int value) {
        
        f3_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 f3 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearF3() {
        bitField0_ = (bitField0_ & ~0x00000004);
        f3_ = 0;
        onChanged();
        return this;
      }

      private int f4_ ;
      /**
       * <code>int32 f4 = 4;</code>
       * @return The f4.
       */
      @java.lang.Override
      public int getF4() {
        return f4_;
      }
      /**
       * <code>int32 f4 = 4;</code>
       * @param value The f4 to set.
       * @return This builder for chaining.
       */
      public Builder setF4(int value) {
        
        f4_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 f4 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearF4() {
        bitField0_ = (bitField0_ & ~0x00000008);
        f4_ = 0;
        onChanged();
        return this;
      }

      private long fileSizeBytes_ ;
      /**
       * <code>int64 file_size_bytes = 7;</code>
       * @return The fileSizeBytes.
       */
      @java.lang.Override
      public long getFileSizeBytes() {
        return fileSizeBytes_;
      }
      /**
       * <code>int64 file_size_bytes = 7;</code>
       * @param value The fileSizeBytes to set.
       * @return This builder for chaining.
       */
      public Builder setFileSizeBytes(long value) {
        
        fileSizeBytes_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int64 file_size_bytes = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileSizeBytes() {
        bitField0_ = (bitField0_ & ~0x00000010);
        fileSizeBytes_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gphotos.GetUploadToken)
    }

    // @@protoc_insertion_point(class_scope:gphotos.GetUploadToken)
    private static final gphotos.GetUploadTokenOuterClass.GetUploadToken DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new gphotos.GetUploadTokenOuterClass.GetUploadToken();
    }

    public static gphotos.GetUploadTokenOuterClass.GetUploadToken getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetUploadToken>
        PARSER = new com.google.protobuf.AbstractParser<GetUploadToken>() {
      @java.lang.Override
      public GetUploadToken parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetUploadToken> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetUploadToken> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public gphotos.GetUploadTokenOuterClass.GetUploadToken getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gphotos_GetUploadToken_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gphotos_GetUploadToken_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024GetUploadToken.proto\022\007gphotos\"Y\n\016GetUp" +
      "loadToken\022\n\n\002f1\030\001 \001(\005\022\n\n\002f2\030\002 \001(\005\022\n\n\002f3\030" +
      "\003 \001(\005\022\n\n\002f4\030\004 \001(\005\022\027\n\017file_size_bytes\030\007 \001" +
      "(\003B#\n\007gphotosB\030GetUploadTokenOuterClassb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gphotos_GetUploadToken_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gphotos_GetUploadToken_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gphotos_GetUploadToken_descriptor,
        new java.lang.String[] { "F1", "F2", "F3", "F4", "FileSizeBytes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
