// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HashCheck.proto

package gphotos;

public final class HashCheckOuterClass {
  private HashCheckOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HashCheckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gphotos.HashCheck)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.gphotos.HashCheck.Field1Type field1 = 1;</code>
     * @return Whether the field1 field is set.
     */
    boolean hasField1();
    /**
     * <code>.gphotos.HashCheck.Field1Type field1 = 1;</code>
     * @return The field1.
     */
    gphotos.HashCheckOuterClass.HashCheck.Field1Type getField1();
    /**
     * <code>.gphotos.HashCheck.Field1Type field1 = 1;</code>
     */
    gphotos.HashCheckOuterClass.HashCheck.Field1TypeOrBuilder getField1OrBuilder();
  }
  /**
   * Protobuf type {@code gphotos.HashCheck}
   */
  public static final class HashCheck extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gphotos.HashCheck)
      HashCheckOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HashCheck.newBuilder() to construct.
    private HashCheck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HashCheck() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HashCheck();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gphotos.HashCheckOuterClass.HashCheck.class, gphotos.HashCheckOuterClass.HashCheck.Builder.class);
    }

    public interface Field1TypeOrBuilder extends
        // @@protoc_insertion_point(interface_extends:gphotos.HashCheck.Field1Type)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.gphotos.HashCheck.Field1Type.InnerField1Type field1 = 1;</code>
       * @return Whether the field1 field is set.
       */
      boolean hasField1();
      /**
       * <code>.gphotos.HashCheck.Field1Type.InnerField1Type field1 = 1;</code>
       * @return The field1.
       */
      gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type getField1();
      /**
       * <code>.gphotos.HashCheck.Field1Type.InnerField1Type field1 = 1;</code>
       */
      gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1TypeOrBuilder getField1OrBuilder();

      /**
       * <code>.gphotos.HashCheck.Field1Type.InnerField2Type field2 = 2;</code>
       * @return Whether the field2 field is set.
       */
      boolean hasField2();
      /**
       * <code>.gphotos.HashCheck.Field1Type.InnerField2Type field2 = 2;</code>
       * @return The field2.
       */
      gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type getField2();
      /**
       * <code>.gphotos.HashCheck.Field1Type.InnerField2Type field2 = 2;</code>
       */
      gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2TypeOrBuilder getField2OrBuilder();
    }
    /**
     * Protobuf type {@code gphotos.HashCheck.Field1Type}
     */
    public static final class Field1Type extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:gphotos.HashCheck.Field1Type)
        Field1TypeOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Field1Type.newBuilder() to construct.
      private Field1Type(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Field1Type() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Field1Type();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_Field1Type_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_Field1Type_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gphotos.HashCheckOuterClass.HashCheck.Field1Type.class, gphotos.HashCheckOuterClass.HashCheck.Field1Type.Builder.class);
      }

      public interface InnerField1TypeOrBuilder extends
          // @@protoc_insertion_point(interface_extends:gphotos.HashCheck.Field1Type.InnerField1Type)
          com.google.protobuf.MessageOrBuilder {

        /**
         * <code>bytes sha1_hash = 1;</code>
         * @return The sha1Hash.
         */
        com.google.protobuf.ByteString getSha1Hash();
      }
      /**
       * Protobuf type {@code gphotos.HashCheck.Field1Type.InnerField1Type}
       */
      public static final class InnerField1Type extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:gphotos.HashCheck.Field1Type.InnerField1Type)
          InnerField1TypeOrBuilder {
      private static final long serialVersionUID = 0L;
        // Use InnerField1Type.newBuilder() to construct.
        private InnerField1Type(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
          super(builder);
        }
        private InnerField1Type() {
          sha1Hash_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
          return new InnerField1Type();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
          return this.unknownFields;
        }
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_Field1Type_InnerField1Type_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_Field1Type_InnerField1Type_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type.class, gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type.Builder.class);
        }

        public static final int SHA1_HASH_FIELD_NUMBER = 1;
        private com.google.protobuf.ByteString sha1Hash_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>bytes sha1_hash = 1;</code>
         * @return The sha1Hash.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getSha1Hash() {
          return sha1Hash_;
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return true;
          if (isInitialized == 0) return false;

          memoizedIsInitialized = 1;
          return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          if (!sha1Hash_.isEmpty()) {
            output.writeBytes(1, sha1Hash_);
          }
          getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
          int size = memoizedSize;
          if (size != -1) return size;

          size = 0;
          if (!sha1Hash_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
              .computeBytesSize(1, sha1Hash_);
          }
          size += getUnknownFields().getSerializedSize();
          memoizedSize = size;
          return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
          if (obj == this) {
           return true;
          }
          if (!(obj instanceof gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type)) {
            return super.equals(obj);
          }
          gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type other = (gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type) obj;

          if (!getSha1Hash()
              .equals(other.getSha1Hash())) return false;
          if (!getUnknownFields().equals(other.getUnknownFields())) return false;
          return true;
        }

        @java.lang.Override
        public int hashCode() {
          if (memoizedHashCode != 0) {
            return memoizedHashCode;
          }
          int hash = 41;
          hash = (19 * hash) + getDescriptor().hashCode();
          hash = (37 * hash) + SHA1_HASH_FIELD_NUMBER;
          hash = (53 * hash) + getSha1Hash().hashCode();
          hash = (29 * hash) + getUnknownFields().hashCode();
          memoizedHashCode = hash;
          return hash;
        }

        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
          return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type prototype) {
          return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
          return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          Builder builder = new Builder(parent);
          return builder;
        }
        /**
         * Protobuf type {@code gphotos.HashCheck.Field1Type.InnerField1Type}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:gphotos.HashCheck.Field1Type.InnerField1Type)
            gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1TypeOrBuilder {
          public static final com.google.protobuf.Descriptors.Descriptor
              getDescriptor() {
            return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_Field1Type_InnerField1Type_descriptor;
          }

          @java.lang.Override
          protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
              internalGetFieldAccessorTable() {
            return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_Field1Type_InnerField1Type_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type.class, gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type.Builder.class);
          }

          // Construct using gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type.newBuilder()
          private Builder() {

          }

          private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);

          }
          @java.lang.Override
          public Builder clear() {
            super.clear();
            bitField0_ = 0;
            sha1Hash_ = com.google.protobuf.ByteString.EMPTY;
            return this;
          }

          @java.lang.Override
          public com.google.protobuf.Descriptors.Descriptor
              getDescriptorForType() {
            return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_Field1Type_InnerField1Type_descriptor;
          }

          @java.lang.Override
          public gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type getDefaultInstanceForType() {
            return gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type.getDefaultInstance();
          }

          @java.lang.Override
          public gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type build() {
            gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return result;
          }

          @java.lang.Override
          public gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type buildPartial() {
            gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type result = new gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type(this);
            if (bitField0_ != 0) { buildPartial0(result); }
            onBuilt();
            return result;
          }

          private void buildPartial0(gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
              result.sha1Hash_ = sha1Hash_;
            }
          }

          @java.lang.Override
          public Builder clone() {
            return super.clone();
          }
          @java.lang.Override
          public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
            return super.setField(field, value);
          }
          @java.lang.Override
          public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
          }
          @java.lang.Override
          public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
          }
          @java.lang.Override
          public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
          }
          @java.lang.Override
          public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
            return super.addRepeatedField(field, value);
          }
          @java.lang.Override
          public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type) {
              return mergeFrom((gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type)other);
            } else {
              super.mergeFrom(other);
              return this;
            }
          }

          public Builder mergeFrom(gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type other) {
            if (other == gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type.getDefaultInstance()) return this;
            if (other.getSha1Hash() != com.google.protobuf.ByteString.EMPTY) {
              setSha1Hash(other.getSha1Hash());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
          }

          @java.lang.Override
          public final boolean isInitialized() {
            return true;
          }

          @java.lang.Override
          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            if (extensionRegistry == null) {
              throw new java.lang.NullPointerException();
            }
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  case 10: {
                    sha1Hash_ = input.readBytes();
                    bitField0_ |= 0x00000001;
                    break;
                  } // case 10
                  default: {
                    if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                      done = true; // was an endgroup tag
                    }
                    break;
                  } // default:
                } // switch (tag)
              } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw e.unwrapIOException();
            } finally {
              onChanged();
            } // finally
            return this;
          }
          private int bitField0_;

          private com.google.protobuf.ByteString sha1Hash_ = com.google.protobuf.ByteString.EMPTY;
          /**
           * <code>bytes sha1_hash = 1;</code>
           * @return The sha1Hash.
           */
          @java.lang.Override
          public com.google.protobuf.ByteString getSha1Hash() {
            return sha1Hash_;
          }
          /**
           * <code>bytes sha1_hash = 1;</code>
           * @param value The sha1Hash to set.
           * @return This builder for chaining.
           */
          public Builder setSha1Hash(com.google.protobuf.ByteString value) {
            if (value == null) { throw new NullPointerException(); }
            sha1Hash_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
          }
          /**
           * <code>bytes sha1_hash = 1;</code>
           * @return This builder for chaining.
           */
          public Builder clearSha1Hash() {
            bitField0_ = (bitField0_ & ~0x00000001);
            sha1Hash_ = getDefaultInstance().getSha1Hash();
            onChanged();
            return this;
          }
          @java.lang.Override
          public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
          }

          @java.lang.Override
          public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
          }


          // @@protoc_insertion_point(builder_scope:gphotos.HashCheck.Field1Type.InnerField1Type)
        }

        // @@protoc_insertion_point(class_scope:gphotos.HashCheck.Field1Type.InnerField1Type)
        private static final gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type DEFAULT_INSTANCE;
        static {
          DEFAULT_INSTANCE = new gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type();
        }

        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type getDefaultInstance() {
          return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<InnerField1Type>
            PARSER = new com.google.protobuf.AbstractParser<InnerField1Type>() {
          @java.lang.Override
          public InnerField1Type parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
              builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
              throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
              throw new com.google.protobuf.InvalidProtocolBufferException(e)
                  .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
          }
        };

        public static com.google.protobuf.Parser<InnerField1Type> parser() {
          return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<InnerField1Type> getParserForType() {
          return PARSER;
        }

        @java.lang.Override
        public gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type getDefaultInstanceForType() {
          return DEFAULT_INSTANCE;
        }

      }

      public interface InnerField2TypeOrBuilder extends
          // @@protoc_insertion_point(interface_extends:gphotos.HashCheck.Field1Type.InnerField2Type)
          com.google.protobuf.MessageOrBuilder {
      }
      /**
       * Protobuf type {@code gphotos.HashCheck.Field1Type.InnerField2Type}
       */
      public static final class InnerField2Type extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:gphotos.HashCheck.Field1Type.InnerField2Type)
          InnerField2TypeOrBuilder {
      private static final long serialVersionUID = 0L;
        // Use InnerField2Type.newBuilder() to construct.
        private InnerField2Type(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
          super(builder);
        }
        private InnerField2Type() {
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
          return new InnerField2Type();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
          return this.unknownFields;
        }
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_Field1Type_InnerField2Type_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_Field1Type_InnerField2Type_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type.class, gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type.Builder.class);
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return true;
          if (isInitialized == 0) return false;

          memoizedIsInitialized = 1;
          return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
          int size = memoizedSize;
          if (size != -1) return size;

          size = 0;
          size += getUnknownFields().getSerializedSize();
          memoizedSize = size;
          return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
          if (obj == this) {
           return true;
          }
          if (!(obj instanceof gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type)) {
            return super.equals(obj);
          }
          gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type other = (gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type) obj;

          if (!getUnknownFields().equals(other.getUnknownFields())) return false;
          return true;
        }

        @java.lang.Override
        public int hashCode() {
          if (memoizedHashCode != 0) {
            return memoizedHashCode;
          }
          int hash = 41;
          hash = (19 * hash) + getDescriptor().hashCode();
          hash = (29 * hash) + getUnknownFields().hashCode();
          memoizedHashCode = hash;
          return hash;
        }

        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
        }
        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
          return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type prototype) {
          return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
          return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          Builder builder = new Builder(parent);
          return builder;
        }
        /**
         * Protobuf type {@code gphotos.HashCheck.Field1Type.InnerField2Type}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:gphotos.HashCheck.Field1Type.InnerField2Type)
            gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2TypeOrBuilder {
          public static final com.google.protobuf.Descriptors.Descriptor
              getDescriptor() {
            return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_Field1Type_InnerField2Type_descriptor;
          }

          @java.lang.Override
          protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
              internalGetFieldAccessorTable() {
            return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_Field1Type_InnerField2Type_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type.class, gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type.Builder.class);
          }

          // Construct using gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type.newBuilder()
          private Builder() {

          }

          private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);

          }
          @java.lang.Override
          public Builder clear() {
            super.clear();
            return this;
          }

          @java.lang.Override
          public com.google.protobuf.Descriptors.Descriptor
              getDescriptorForType() {
            return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_Field1Type_InnerField2Type_descriptor;
          }

          @java.lang.Override
          public gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type getDefaultInstanceForType() {
            return gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type.getDefaultInstance();
          }

          @java.lang.Override
          public gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type build() {
            gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return result;
          }

          @java.lang.Override
          public gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type buildPartial() {
            gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type result = new gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type(this);
            onBuilt();
            return result;
          }

          @java.lang.Override
          public Builder clone() {
            return super.clone();
          }
          @java.lang.Override
          public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
            return super.setField(field, value);
          }
          @java.lang.Override
          public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
          }
          @java.lang.Override
          public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
          }
          @java.lang.Override
          public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
          }
          @java.lang.Override
          public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
            return super.addRepeatedField(field, value);
          }
          @java.lang.Override
          public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type) {
              return mergeFrom((gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type)other);
            } else {
              super.mergeFrom(other);
              return this;
            }
          }

          public Builder mergeFrom(gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type other) {
            if (other == gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type.getDefaultInstance()) return this;
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
          }

          @java.lang.Override
          public final boolean isInitialized() {
            return true;
          }

          @java.lang.Override
          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            if (extensionRegistry == null) {
              throw new java.lang.NullPointerException();
            }
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                      done = true; // was an endgroup tag
                    }
                    break;
                  } // default:
                } // switch (tag)
              } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw e.unwrapIOException();
            } finally {
              onChanged();
            } // finally
            return this;
          }
          @java.lang.Override
          public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
          }

          @java.lang.Override
          public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
          }


          // @@protoc_insertion_point(builder_scope:gphotos.HashCheck.Field1Type.InnerField2Type)
        }

        // @@protoc_insertion_point(class_scope:gphotos.HashCheck.Field1Type.InnerField2Type)
        private static final gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type DEFAULT_INSTANCE;
        static {
          DEFAULT_INSTANCE = new gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type();
        }

        public static gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type getDefaultInstance() {
          return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<InnerField2Type>
            PARSER = new com.google.protobuf.AbstractParser<InnerField2Type>() {
          @java.lang.Override
          public InnerField2Type parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
              builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
              throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
              throw new com.google.protobuf.InvalidProtocolBufferException(e)
                  .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
          }
        };

        public static com.google.protobuf.Parser<InnerField2Type> parser() {
          return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<InnerField2Type> getParserForType() {
          return PARSER;
        }

        @java.lang.Override
        public gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type getDefaultInstanceForType() {
          return DEFAULT_INSTANCE;
        }

      }

      public static final int FIELD1_FIELD_NUMBER = 1;
      private gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type field1_;
      /**
       * <code>.gphotos.HashCheck.Field1Type.InnerField1Type field1 = 1;</code>
       * @return Whether the field1 field is set.
       */
      @java.lang.Override
      public boolean hasField1() {
        return field1_ != null;
      }
      /**
       * <code>.gphotos.HashCheck.Field1Type.InnerField1Type field1 = 1;</code>
       * @return The field1.
       */
      @java.lang.Override
      public gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type getField1() {
        return field1_ == null ? gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type.getDefaultInstance() : field1_;
      }
      /**
       * <code>.gphotos.HashCheck.Field1Type.InnerField1Type field1 = 1;</code>
       */
      @java.lang.Override
      public gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1TypeOrBuilder getField1OrBuilder() {
        return field1_ == null ? gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type.getDefaultInstance() : field1_;
      }

      public static final int FIELD2_FIELD_NUMBER = 2;
      private gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type field2_;
      /**
       * <code>.gphotos.HashCheck.Field1Type.InnerField2Type field2 = 2;</code>
       * @return Whether the field2 field is set.
       */
      @java.lang.Override
      public boolean hasField2() {
        return field2_ != null;
      }
      /**
       * <code>.gphotos.HashCheck.Field1Type.InnerField2Type field2 = 2;</code>
       * @return The field2.
       */
      @java.lang.Override
      public gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type getField2() {
        return field2_ == null ? gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type.getDefaultInstance() : field2_;
      }
      /**
       * <code>.gphotos.HashCheck.Field1Type.InnerField2Type field2 = 2;</code>
       */
      @java.lang.Override
      public gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2TypeOrBuilder getField2OrBuilder() {
        return field2_ == null ? gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type.getDefaultInstance() : field2_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (field1_ != null) {
          output.writeMessage(1, getField1());
        }
        if (field2_ != null) {
          output.writeMessage(2, getField2());
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (field1_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, getField1());
        }
        if (field2_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, getField2());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof gphotos.HashCheckOuterClass.HashCheck.Field1Type)) {
          return super.equals(obj);
        }
        gphotos.HashCheckOuterClass.HashCheck.Field1Type other = (gphotos.HashCheckOuterClass.HashCheck.Field1Type) obj;

        if (hasField1() != other.hasField1()) return false;
        if (hasField1()) {
          if (!getField1()
              .equals(other.getField1())) return false;
        }
        if (hasField2() != other.hasField2()) return false;
        if (hasField2()) {
          if (!getField2()
              .equals(other.getField2())) return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasField1()) {
          hash = (37 * hash) + FIELD1_FIELD_NUMBER;
          hash = (53 * hash) + getField1().hashCode();
        }
        if (hasField2()) {
          hash = (37 * hash) + FIELD2_FIELD_NUMBER;
          hash = (53 * hash) + getField2().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static gphotos.HashCheckOuterClass.HashCheck.Field1Type parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gphotos.HashCheckOuterClass.HashCheck.Field1Type parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gphotos.HashCheckOuterClass.HashCheck.Field1Type parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gphotos.HashCheckOuterClass.HashCheck.Field1Type parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gphotos.HashCheckOuterClass.HashCheck.Field1Type parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gphotos.HashCheckOuterClass.HashCheck.Field1Type parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gphotos.HashCheckOuterClass.HashCheck.Field1Type parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static gphotos.HashCheckOuterClass.HashCheck.Field1Type parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static gphotos.HashCheckOuterClass.HashCheck.Field1Type parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static gphotos.HashCheckOuterClass.HashCheck.Field1Type parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static gphotos.HashCheckOuterClass.HashCheck.Field1Type parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static gphotos.HashCheckOuterClass.HashCheck.Field1Type parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(gphotos.HashCheckOuterClass.HashCheck.Field1Type prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code gphotos.HashCheck.Field1Type}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:gphotos.HashCheck.Field1Type)
          gphotos.HashCheckOuterClass.HashCheck.Field1TypeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_Field1Type_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_Field1Type_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  gphotos.HashCheckOuterClass.HashCheck.Field1Type.class, gphotos.HashCheckOuterClass.HashCheck.Field1Type.Builder.class);
        }

        // Construct using gphotos.HashCheckOuterClass.HashCheck.Field1Type.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          field1_ = null;
          if (field1Builder_ != null) {
            field1Builder_.dispose();
            field1Builder_ = null;
          }
          field2_ = null;
          if (field2Builder_ != null) {
            field2Builder_.dispose();
            field2Builder_ = null;
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_Field1Type_descriptor;
        }

        @java.lang.Override
        public gphotos.HashCheckOuterClass.HashCheck.Field1Type getDefaultInstanceForType() {
          return gphotos.HashCheckOuterClass.HashCheck.Field1Type.getDefaultInstance();
        }

        @java.lang.Override
        public gphotos.HashCheckOuterClass.HashCheck.Field1Type build() {
          gphotos.HashCheckOuterClass.HashCheck.Field1Type result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public gphotos.HashCheckOuterClass.HashCheck.Field1Type buildPartial() {
          gphotos.HashCheckOuterClass.HashCheck.Field1Type result = new gphotos.HashCheckOuterClass.HashCheck.Field1Type(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(gphotos.HashCheckOuterClass.HashCheck.Field1Type result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.field1_ = field1Builder_ == null
                ? field1_
                : field1Builder_.build();
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.field2_ = field2Builder_ == null
                ? field2_
                : field2Builder_.build();
          }
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof gphotos.HashCheckOuterClass.HashCheck.Field1Type) {
            return mergeFrom((gphotos.HashCheckOuterClass.HashCheck.Field1Type)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(gphotos.HashCheckOuterClass.HashCheck.Field1Type other) {
          if (other == gphotos.HashCheckOuterClass.HashCheck.Field1Type.getDefaultInstance()) return this;
          if (other.hasField1()) {
            mergeField1(other.getField1());
          }
          if (other.hasField2()) {
            mergeField2(other.getField2());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  input.readMessage(
                      getField1FieldBuilder().getBuilder(),
                      extensionRegistry);
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 18: {
                  input.readMessage(
                      getField2FieldBuilder().getBuilder(),
                      extensionRegistry);
                  bitField0_ |= 0x00000002;
                  break;
                } // case 18
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type field1_;
        private com.google.protobuf.SingleFieldBuilderV3<
            gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type, gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type.Builder, gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1TypeOrBuilder> field1Builder_;
        /**
         * <code>.gphotos.HashCheck.Field1Type.InnerField1Type field1 = 1;</code>
         * @return Whether the field1 field is set.
         */
        public boolean hasField1() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>.gphotos.HashCheck.Field1Type.InnerField1Type field1 = 1;</code>
         * @return The field1.
         */
        public gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type getField1() {
          if (field1Builder_ == null) {
            return field1_ == null ? gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type.getDefaultInstance() : field1_;
          } else {
            return field1Builder_.getMessage();
          }
        }
        /**
         * <code>.gphotos.HashCheck.Field1Type.InnerField1Type field1 = 1;</code>
         */
        public Builder setField1(gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type value) {
          if (field1Builder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            field1_ = value;
          } else {
            field1Builder_.setMessage(value);
          }
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>.gphotos.HashCheck.Field1Type.InnerField1Type field1 = 1;</code>
         */
        public Builder setField1(
            gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type.Builder builderForValue) {
          if (field1Builder_ == null) {
            field1_ = builderForValue.build();
          } else {
            field1Builder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>.gphotos.HashCheck.Field1Type.InnerField1Type field1 = 1;</code>
         */
        public Builder mergeField1(gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type value) {
          if (field1Builder_ == null) {
            if (((bitField0_ & 0x00000001) != 0) &&
              field1_ != null &&
              field1_ != gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type.getDefaultInstance()) {
              getField1Builder().mergeFrom(value);
            } else {
              field1_ = value;
            }
          } else {
            field1Builder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>.gphotos.HashCheck.Field1Type.InnerField1Type field1 = 1;</code>
         */
        public Builder clearField1() {
          bitField0_ = (bitField0_ & ~0x00000001);
          field1_ = null;
          if (field1Builder_ != null) {
            field1Builder_.dispose();
            field1Builder_ = null;
          }
          onChanged();
          return this;
        }
        /**
         * <code>.gphotos.HashCheck.Field1Type.InnerField1Type field1 = 1;</code>
         */
        public gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type.Builder getField1Builder() {
          bitField0_ |= 0x00000001;
          onChanged();
          return getField1FieldBuilder().getBuilder();
        }
        /**
         * <code>.gphotos.HashCheck.Field1Type.InnerField1Type field1 = 1;</code>
         */
        public gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1TypeOrBuilder getField1OrBuilder() {
          if (field1Builder_ != null) {
            return field1Builder_.getMessageOrBuilder();
          } else {
            return field1_ == null ?
                gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type.getDefaultInstance() : field1_;
          }
        }
        /**
         * <code>.gphotos.HashCheck.Field1Type.InnerField1Type field1 = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type, gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type.Builder, gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1TypeOrBuilder> 
            getField1FieldBuilder() {
          if (field1Builder_ == null) {
            field1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
                gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type, gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1Type.Builder, gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField1TypeOrBuilder>(
                    getField1(),
                    getParentForChildren(),
                    isClean());
            field1_ = null;
          }
          return field1Builder_;
        }

        private gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type field2_;
        private com.google.protobuf.SingleFieldBuilderV3<
            gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type, gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type.Builder, gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2TypeOrBuilder> field2Builder_;
        /**
         * <code>.gphotos.HashCheck.Field1Type.InnerField2Type field2 = 2;</code>
         * @return Whether the field2 field is set.
         */
        public boolean hasField2() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>.gphotos.HashCheck.Field1Type.InnerField2Type field2 = 2;</code>
         * @return The field2.
         */
        public gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type getField2() {
          if (field2Builder_ == null) {
            return field2_ == null ? gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type.getDefaultInstance() : field2_;
          } else {
            return field2Builder_.getMessage();
          }
        }
        /**
         * <code>.gphotos.HashCheck.Field1Type.InnerField2Type field2 = 2;</code>
         */
        public Builder setField2(gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type value) {
          if (field2Builder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            field2_ = value;
          } else {
            field2Builder_.setMessage(value);
          }
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>.gphotos.HashCheck.Field1Type.InnerField2Type field2 = 2;</code>
         */
        public Builder setField2(
            gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type.Builder builderForValue) {
          if (field2Builder_ == null) {
            field2_ = builderForValue.build();
          } else {
            field2Builder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>.gphotos.HashCheck.Field1Type.InnerField2Type field2 = 2;</code>
         */
        public Builder mergeField2(gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type value) {
          if (field2Builder_ == null) {
            if (((bitField0_ & 0x00000002) != 0) &&
              field2_ != null &&
              field2_ != gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type.getDefaultInstance()) {
              getField2Builder().mergeFrom(value);
            } else {
              field2_ = value;
            }
          } else {
            field2Builder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>.gphotos.HashCheck.Field1Type.InnerField2Type field2 = 2;</code>
         */
        public Builder clearField2() {
          bitField0_ = (bitField0_ & ~0x00000002);
          field2_ = null;
          if (field2Builder_ != null) {
            field2Builder_.dispose();
            field2Builder_ = null;
          }
          onChanged();
          return this;
        }
        /**
         * <code>.gphotos.HashCheck.Field1Type.InnerField2Type field2 = 2;</code>
         */
        public gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type.Builder getField2Builder() {
          bitField0_ |= 0x00000002;
          onChanged();
          return getField2FieldBuilder().getBuilder();
        }
        /**
         * <code>.gphotos.HashCheck.Field1Type.InnerField2Type field2 = 2;</code>
         */
        public gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2TypeOrBuilder getField2OrBuilder() {
          if (field2Builder_ != null) {
            return field2Builder_.getMessageOrBuilder();
          } else {
            return field2_ == null ?
                gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type.getDefaultInstance() : field2_;
          }
        }
        /**
         * <code>.gphotos.HashCheck.Field1Type.InnerField2Type field2 = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
            gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type, gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type.Builder, gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2TypeOrBuilder> 
            getField2FieldBuilder() {
          if (field2Builder_ == null) {
            field2Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
                gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type, gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2Type.Builder, gphotos.HashCheckOuterClass.HashCheck.Field1Type.InnerField2TypeOrBuilder>(
                    getField2(),
                    getParentForChildren(),
                    isClean());
            field2_ = null;
          }
          return field2Builder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:gphotos.HashCheck.Field1Type)
      }

      // @@protoc_insertion_point(class_scope:gphotos.HashCheck.Field1Type)
      private static final gphotos.HashCheckOuterClass.HashCheck.Field1Type DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new gphotos.HashCheckOuterClass.HashCheck.Field1Type();
      }

      public static gphotos.HashCheckOuterClass.HashCheck.Field1Type getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Field1Type>
          PARSER = new com.google.protobuf.AbstractParser<Field1Type>() {
        @java.lang.Override
        public Field1Type parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<Field1Type> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Field1Type> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public gphotos.HashCheckOuterClass.HashCheck.Field1Type getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int FIELD1_FIELD_NUMBER = 1;
    private gphotos.HashCheckOuterClass.HashCheck.Field1Type field1_;
    /**
     * <code>.gphotos.HashCheck.Field1Type field1 = 1;</code>
     * @return Whether the field1 field is set.
     */
    @java.lang.Override
    public boolean hasField1() {
      return field1_ != null;
    }
    /**
     * <code>.gphotos.HashCheck.Field1Type field1 = 1;</code>
     * @return The field1.
     */
    @java.lang.Override
    public gphotos.HashCheckOuterClass.HashCheck.Field1Type getField1() {
      return field1_ == null ? gphotos.HashCheckOuterClass.HashCheck.Field1Type.getDefaultInstance() : field1_;
    }
    /**
     * <code>.gphotos.HashCheck.Field1Type field1 = 1;</code>
     */
    @java.lang.Override
    public gphotos.HashCheckOuterClass.HashCheck.Field1TypeOrBuilder getField1OrBuilder() {
      return field1_ == null ? gphotos.HashCheckOuterClass.HashCheck.Field1Type.getDefaultInstance() : field1_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (field1_ != null) {
        output.writeMessage(1, getField1());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (field1_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getField1());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof gphotos.HashCheckOuterClass.HashCheck)) {
        return super.equals(obj);
      }
      gphotos.HashCheckOuterClass.HashCheck other = (gphotos.HashCheckOuterClass.HashCheck) obj;

      if (hasField1() != other.hasField1()) return false;
      if (hasField1()) {
        if (!getField1()
            .equals(other.getField1())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasField1()) {
        hash = (37 * hash) + FIELD1_FIELD_NUMBER;
        hash = (53 * hash) + getField1().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static gphotos.HashCheckOuterClass.HashCheck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gphotos.HashCheckOuterClass.HashCheck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gphotos.HashCheckOuterClass.HashCheck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gphotos.HashCheckOuterClass.HashCheck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gphotos.HashCheckOuterClass.HashCheck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gphotos.HashCheckOuterClass.HashCheck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gphotos.HashCheckOuterClass.HashCheck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gphotos.HashCheckOuterClass.HashCheck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static gphotos.HashCheckOuterClass.HashCheck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static gphotos.HashCheckOuterClass.HashCheck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static gphotos.HashCheckOuterClass.HashCheck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gphotos.HashCheckOuterClass.HashCheck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(gphotos.HashCheckOuterClass.HashCheck prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gphotos.HashCheck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gphotos.HashCheck)
        gphotos.HashCheckOuterClass.HashCheckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gphotos.HashCheckOuterClass.HashCheck.class, gphotos.HashCheckOuterClass.HashCheck.Builder.class);
      }

      // Construct using gphotos.HashCheckOuterClass.HashCheck.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        field1_ = null;
        if (field1Builder_ != null) {
          field1Builder_.dispose();
          field1Builder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gphotos.HashCheckOuterClass.internal_static_gphotos_HashCheck_descriptor;
      }

      @java.lang.Override
      public gphotos.HashCheckOuterClass.HashCheck getDefaultInstanceForType() {
        return gphotos.HashCheckOuterClass.HashCheck.getDefaultInstance();
      }

      @java.lang.Override
      public gphotos.HashCheckOuterClass.HashCheck build() {
        gphotos.HashCheckOuterClass.HashCheck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public gphotos.HashCheckOuterClass.HashCheck buildPartial() {
        gphotos.HashCheckOuterClass.HashCheck result = new gphotos.HashCheckOuterClass.HashCheck(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(gphotos.HashCheckOuterClass.HashCheck result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.field1_ = field1Builder_ == null
              ? field1_
              : field1Builder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gphotos.HashCheckOuterClass.HashCheck) {
          return mergeFrom((gphotos.HashCheckOuterClass.HashCheck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gphotos.HashCheckOuterClass.HashCheck other) {
        if (other == gphotos.HashCheckOuterClass.HashCheck.getDefaultInstance()) return this;
        if (other.hasField1()) {
          mergeField1(other.getField1());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getField1FieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private gphotos.HashCheckOuterClass.HashCheck.Field1Type field1_;
      private com.google.protobuf.SingleFieldBuilderV3<
          gphotos.HashCheckOuterClass.HashCheck.Field1Type, gphotos.HashCheckOuterClass.HashCheck.Field1Type.Builder, gphotos.HashCheckOuterClass.HashCheck.Field1TypeOrBuilder> field1Builder_;
      /**
       * <code>.gphotos.HashCheck.Field1Type field1 = 1;</code>
       * @return Whether the field1 field is set.
       */
      public boolean hasField1() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.gphotos.HashCheck.Field1Type field1 = 1;</code>
       * @return The field1.
       */
      public gphotos.HashCheckOuterClass.HashCheck.Field1Type getField1() {
        if (field1Builder_ == null) {
          return field1_ == null ? gphotos.HashCheckOuterClass.HashCheck.Field1Type.getDefaultInstance() : field1_;
        } else {
          return field1Builder_.getMessage();
        }
      }
      /**
       * <code>.gphotos.HashCheck.Field1Type field1 = 1;</code>
       */
      public Builder setField1(gphotos.HashCheckOuterClass.HashCheck.Field1Type value) {
        if (field1Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          field1_ = value;
        } else {
          field1Builder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.gphotos.HashCheck.Field1Type field1 = 1;</code>
       */
      public Builder setField1(
          gphotos.HashCheckOuterClass.HashCheck.Field1Type.Builder builderForValue) {
        if (field1Builder_ == null) {
          field1_ = builderForValue.build();
        } else {
          field1Builder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.gphotos.HashCheck.Field1Type field1 = 1;</code>
       */
      public Builder mergeField1(gphotos.HashCheckOuterClass.HashCheck.Field1Type value) {
        if (field1Builder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            field1_ != null &&
            field1_ != gphotos.HashCheckOuterClass.HashCheck.Field1Type.getDefaultInstance()) {
            getField1Builder().mergeFrom(value);
          } else {
            field1_ = value;
          }
        } else {
          field1Builder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.gphotos.HashCheck.Field1Type field1 = 1;</code>
       */
      public Builder clearField1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        field1_ = null;
        if (field1Builder_ != null) {
          field1Builder_.dispose();
          field1Builder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.gphotos.HashCheck.Field1Type field1 = 1;</code>
       */
      public gphotos.HashCheckOuterClass.HashCheck.Field1Type.Builder getField1Builder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getField1FieldBuilder().getBuilder();
      }
      /**
       * <code>.gphotos.HashCheck.Field1Type field1 = 1;</code>
       */
      public gphotos.HashCheckOuterClass.HashCheck.Field1TypeOrBuilder getField1OrBuilder() {
        if (field1Builder_ != null) {
          return field1Builder_.getMessageOrBuilder();
        } else {
          return field1_ == null ?
              gphotos.HashCheckOuterClass.HashCheck.Field1Type.getDefaultInstance() : field1_;
        }
      }
      /**
       * <code>.gphotos.HashCheck.Field1Type field1 = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          gphotos.HashCheckOuterClass.HashCheck.Field1Type, gphotos.HashCheckOuterClass.HashCheck.Field1Type.Builder, gphotos.HashCheckOuterClass.HashCheck.Field1TypeOrBuilder> 
          getField1FieldBuilder() {
        if (field1Builder_ == null) {
          field1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              gphotos.HashCheckOuterClass.HashCheck.Field1Type, gphotos.HashCheckOuterClass.HashCheck.Field1Type.Builder, gphotos.HashCheckOuterClass.HashCheck.Field1TypeOrBuilder>(
                  getField1(),
                  getParentForChildren(),
                  isClean());
          field1_ = null;
        }
        return field1Builder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:gphotos.HashCheck)
    }

    // @@protoc_insertion_point(class_scope:gphotos.HashCheck)
    private static final gphotos.HashCheckOuterClass.HashCheck DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new gphotos.HashCheckOuterClass.HashCheck();
    }

    public static gphotos.HashCheckOuterClass.HashCheck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HashCheck>
        PARSER = new com.google.protobuf.AbstractParser<HashCheck>() {
      @java.lang.Override
      public HashCheck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HashCheck> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HashCheck> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public gphotos.HashCheckOuterClass.HashCheck getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gphotos_HashCheck_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gphotos_HashCheck_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gphotos_HashCheck_Field1Type_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gphotos_HashCheck_Field1Type_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gphotos_HashCheck_Field1Type_InnerField1Type_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gphotos_HashCheck_Field1Type_InnerField1Type_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gphotos_HashCheck_Field1Type_InnerField2Type_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gphotos_HashCheck_Field1Type_InnerField2Type_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017HashCheck.proto\022\007gphotos\"\200\002\n\tHashCheck" +
      "\022-\n\006field1\030\001 \001(\0132\035.gphotos.HashCheck.Fie" +
      "ld1Type\032\303\001\n\nField1Type\022=\n\006field1\030\001 \001(\0132-" +
      ".gphotos.HashCheck.Field1Type.InnerField" +
      "1Type\022=\n\006field2\030\002 \001(\0132-.gphotos.HashChec" +
      "k.Field1Type.InnerField2Type\032$\n\017InnerFie" +
      "ld1Type\022\021\n\tsha1_hash\030\001 \001(\014\032\021\n\017InnerField" +
      "2TypeB\036\n\007gphotosB\023HashCheckOuterClassb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gphotos_HashCheck_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gphotos_HashCheck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gphotos_HashCheck_descriptor,
        new java.lang.String[] { "Field1", });
    internal_static_gphotos_HashCheck_Field1Type_descriptor =
      internal_static_gphotos_HashCheck_descriptor.getNestedTypes().get(0);
    internal_static_gphotos_HashCheck_Field1Type_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gphotos_HashCheck_Field1Type_descriptor,
        new java.lang.String[] { "Field1", "Field2", });
    internal_static_gphotos_HashCheck_Field1Type_InnerField1Type_descriptor =
      internal_static_gphotos_HashCheck_Field1Type_descriptor.getNestedTypes().get(0);
    internal_static_gphotos_HashCheck_Field1Type_InnerField1Type_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gphotos_HashCheck_Field1Type_InnerField1Type_descriptor,
        new java.lang.String[] { "Sha1Hash", });
    internal_static_gphotos_HashCheck_Field1Type_InnerField2Type_descriptor =
      internal_static_gphotos_HashCheck_Field1Type_descriptor.getNestedTypes().get(1);
    internal_static_gphotos_HashCheck_Field1Type_InnerField2Type_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gphotos_HashCheck_Field1Type_InnerField2Type_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
